import type { DeckCard } from '../lobby/decks'
import type { DeckFormat } from './types'

export interface MetaDeckItem {
  id: string
  name: string
  format: DeckFormat
  archetype: 'Aggro' | 'Midrange' | 'Control' | 'Combo' | 'Ramp' | 'Tribal' | 'Precon'
  colors: ('W' | 'U' | 'B' | 'R' | 'G')[]
  coverCard: DeckCard
  description: string
  tier?: string
  author?: string
  cards: DeckCard[]
  sideboard: DeckCard[]
}

export const META_DECK_CATALOG: MetaDeckItem[] = [
  // =========================================================================
  // STANDARD
  // =========================================================================
  {
    id: 'meta-std-mono-red',
    name: 'Mono Red Aggro',
    format: 'Standard',
    archetype: 'Aggro',
    colors: ['R'],
    coverCard: { cardName: 'Monastery Swiftspear', setCode: 'BRO', cardNumber: '144', amount: 4 },
    description: 'El arquetipo agresivo por excelencia en Standard: daño rápido con chispas y criaturas con Haste.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 20 },
      { cardName: 'Monastery Swiftspear', setCode: 'BRO', cardNumber: '144', amount: 4 },
      { cardName: 'Lightning Strike', setCode: 'DMU', cardNumber: '137', amount: 4 },
      { cardName: 'Play with Fire', setCode: 'MID', cardNumber: '154', amount: 4 },
      { cardName: 'Kumano Faces Kakkazan', setCode: 'NEO', cardNumber: '152', amount: 4 },
      { cardName: 'Shock', setCode: 'M21', cardNumber: '159', amount: 4 },
      { cardName: 'Feldon, Ronom Excavator', setCode: 'BRO', cardNumber: '135', amount: 4 },
      { cardName: 'Squee, Dubious Monarch', setCode: 'DMU', cardNumber: '146', amount: 4 },
      { cardName: 'Charming Scoundrel', setCode: 'WOE', cardNumber: '124', amount: 4 },
      { cardName: 'Bloodthirsty Adversary', setCode: 'MID', cardNumber: '129', amount: 4 },
      { cardName: 'Mishra\'s Foundry', setCode: 'BRO', cardNumber: '265', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Lithomantic Barrage', setCode: 'MOM', cardNumber: '152', amount: 4 },
      { cardName: 'Wrenn\'s Resolve', setCode: 'MOM', cardNumber: '173', amount: 4 },
      { cardName: 'Urabrask\'s Forge', setCode: 'ONE', cardNumber: '153', amount: 4 },
      { cardName: 'Torch the Tower', setCode: 'WOE', cardNumber: '153', amount: 3 },
    ],
  },
  {
    id: 'meta-std-dimir-midrange',
    name: 'Dimir Midrange',
    format: 'Standard',
    archetype: 'Midrange',
    colors: ['U', 'B'],
    coverCard: { cardName: 'Gix, Yawgmoth Praetor', setCode: 'BRO', cardNumber: '95', amount: 4 },
    description: 'Control de mesa con interacción eficiente de Negro y robo de cartas de Azul.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 8 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 10 },
      { cardName: 'Darkslick Shores', setCode: 'ONE', cardNumber: '250', amount: 4 },
      { cardName: 'Underground River', setCode: 'BRO', cardNumber: '267', amount: 4 },
      { cardName: 'Deep-Cavern Bat', setCode: 'LCI', cardNumber: '102', amount: 4 },
      { cardName: 'Gix, Yawgmoth Praetor', setCode: 'BRO', cardNumber: '95', amount: 4 },
      { cardName: 'Preacher of the Schism', setCode: 'LCI', cardNumber: '113', amount: 4 },
      { cardName: 'Cut Down', setCode: 'DMU', cardNumber: '89', amount: 4 },
      { cardName: 'Go for the Throat', setCode: 'BRO', cardNumber: '102', amount: 4 },
      { cardName: 'Make Disappear', setCode: 'SNC', cardNumber: '49', amount: 4 },
      { cardName: 'Faerie Mastermind', setCode: 'MOM', cardNumber: '58', amount: 4 },
      { cardName: 'Aclazotz, Deepest Betrayal', setCode: 'LCI', cardNumber: '88', amount: 2 },
      { cardName: 'Ertai Resurrected', setCode: 'DMU', cardNumber: '199', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Negate', setCode: 'MOM', cardNumber: '68', amount: 4 },
      { cardName: 'Duress', setCode: 'ONE', cardNumber: '92', amount: 4 },
      { cardName: 'Gix\'s Command', setCode: 'BRO', cardNumber: '97', amount: 3 },
      { cardName: 'Tishana\'s Tidebinder', setCode: 'LCI', cardNumber: '81', amount: 4 },
    ],
  },
  {
    id: 'meta-std-domain-ramp',
    name: 'Domain Ramp (Atraxa)',
    format: 'Standard',
    archetype: 'Ramp',
    colors: ['W', 'U', 'B', 'R', 'G'],
    coverCard: { cardName: 'Atraxa, Grand Unifier', setCode: 'ONE', cardNumber: '196', amount: 4 },
    description: 'Acelera maná de los 5 tipos de tierras para bajar a Atraxa y dominar la partida.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 6 },
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 4 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 2 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 2 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 2 },
      { cardName: 'Sunfall', setCode: 'MOM', cardNumber: '40', amount: 4 },
      { cardName: 'Archangel of Wrath', setCode: 'DMU', cardNumber: '3', amount: 4 },
      { cardName: 'Atraxa, Grand Unifier', setCode: 'ONE', cardNumber: '196', amount: 4 },
      { cardName: 'Topiary Stomper', setCode: 'SNC', cardNumber: '160', amount: 4 },
      { cardName: 'Leyline Binding', setCode: 'DMU', cardNumber: '24', amount: 4 },
      { cardName: 'Herd Migration', setCode: 'DMU', cardNumber: '165', amount: 4 },
      { cardName: 'Zuberi, Golden Feather', setCode: 'MIR', cardNumber: '202', amount: 4 },
      { cardName: 'Up the Beanstalk', setCode: 'WOE', cardNumber: '195', amount: 4 },
      { cardName: 'Spirebluff Canal', setCode: 'OTJ', cardNumber: '270', amount: 4 },
      { cardName: 'Overgrown Tomb', setCode: 'GRN', cardNumber: '253', amount: 4 },
      { cardName: 'Cavern of Souls', setCode: 'LCI', cardNumber: '269', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Knockout Blow', setCode: 'SNC', cardNumber: '20', amount: 4 },
      { cardName: 'Negate', setCode: 'MOM', cardNumber: '68', amount: 4 },
      { cardName: 'Elspeth\'s Smite', setCode: 'MOM', cardNumber: '13', amount: 4 },
      { cardName: 'Chrome Host Seedshark', setCode: 'MOM', cardNumber: '51', amount: 3 },
    ],
  },
  {
    id: 'meta-std-golgari-midrange',
    name: 'Golgari Midrange',
    format: 'Standard',
    archetype: 'Midrange',
    colors: ['B', 'G'],
    coverCard: { cardName: 'Mosswood Dreadknight', setCode: 'WOE', cardNumber: '231', amount: 4 },
    description: 'Resistencia pura con Glissa, Sheoldred y ventaja de cartas constante.',
    tier: 'Tier 1.5',
    cards: [
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 10 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 8 },
      { cardName: 'Llanowar Wastes', setCode: 'BRO', cardNumber: '264', amount: 4 },
      { cardName: 'Restless Cottage', setCode: 'WOE', cardNumber: '258', amount: 4 },
      { cardName: 'Mosswood Dreadknight', setCode: 'WOE', cardNumber: '231', amount: 4 },
      { cardName: 'Glissa Sunslayer', setCode: 'ONE', cardNumber: '202', amount: 4 },
      { cardName: 'Sheoldred, the Apocalypse', setCode: 'DMU', cardNumber: '107', amount: 4 },
      { cardName: 'Deep-Cavern Bat', setCode: 'LCI', cardNumber: '102', amount: 4 },
      { cardName: 'Cut Down', setCode: 'DMU', cardNumber: '89', amount: 4 },
      { cardName: 'Go for the Throat', setCode: 'BRO', cardNumber: '102', amount: 4 },
      { cardName: 'Tear Asunder', setCode: 'DMU', cardNumber: '183', amount: 4 },
      { cardName: 'Preacher of the Schism', setCode: 'LCI', cardNumber: '113', amount: 4 },
      { cardName: 'Gix, Yawgmoth Praetor', setCode: 'BRO', cardNumber: '95', amount: 2 },
    ],
    sideboard: [
      { cardName: 'Duress', setCode: 'ONE', cardNumber: '92', amount: 4 },
      { cardName: 'Glistening Deluge', setCode: 'MOM', cardNumber: '107', amount: 4 },
      { cardName: 'Tranquil Frillback', setCode: 'MAT', cardNumber: '24', amount: 4 },
      { cardName: 'Gix\'s Command', setCode: 'BRO', cardNumber: '97', amount: 3 },
    ],
  },
  {
    id: 'meta-std-boros-convoke',
    name: 'Boros Convoke',
    format: 'Standard',
    archetype: 'Aggro',
    colors: ['W', 'R'],
    coverCard: { cardName: 'Knight-Errant of Eos', setCode: 'MOM', cardNumber: '26', amount: 4 },
    description: 'Genera artefactos y trasgos en turno 1 para convocar a Knight-Errant en turno 2.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 8 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 8 },
      { cardName: 'Inspiring Vantage', setCode: 'OTJ', cardNumber: '269', amount: 4 },
      { cardName: 'Battlefield Forge', setCode: 'BRO', cardNumber: '257', amount: 4 },
      { cardName: 'Voldaren Epicure', setCode: 'VOW', cardNumber: '182', amount: 4 },
      { cardName: 'Yotian Frontliner', setCode: 'BRO', cardNumber: '42', amount: 4 },
      { cardName: 'Gleeful Demolition', setCode: 'ONE', cardNumber: '134', amount: 4 },
      { cardName: 'Resolute Reinforcements', setCode: 'DMU', cardNumber: '29', amount: 4 },
      { cardName: 'Knight-Errant of Eos', setCode: 'MOM', cardNumber: '26', amount: 4 },
      { cardName: 'Imodane\'s Recruiter', setCode: 'WOE', cardNumber: '229', amount: 4 },
      { cardName: 'Warden of the Inner Sky', setCode: 'LCI', cardNumber: '43', amount: 4 },
      { cardName: 'Case of the Gateway Express', setCode: 'MKM', cardNumber: '8', amount: 4 },
      { cardName: 'Lightning Strike', setCode: 'DMU', cardNumber: '137', amount: 4 },
      { cardName: 'Mishra\'s Foundry', setCode: 'BRO', cardNumber: '265', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Lithomantic Barrage', setCode: 'MOM', cardNumber: '152', amount: 4 },
      { cardName: 'Thalia, Guardian of Thraben', setCode: 'VOW', cardNumber: '38', amount: 4 },
      { cardName: 'Get Lost', setCode: 'LCI', cardNumber: '14', amount: 4 },
      { cardName: 'Wrenn\'s Resolve', setCode: 'MOM', cardNumber: '173', amount: 3 },
    ],
  },

  // =========================================================================
  // MODERN
  // =========================================================================
  {
    id: 'meta-mod-murktide',
    name: 'Izzet Murktide',
    format: 'Modern',
    archetype: 'Midrange',
    colors: ['U', 'R'],
    coverCard: { cardName: 'Murktide Regent', setCode: 'MH2', cardNumber: '52', amount: 4 },
    description: 'El mazo tempo más icónico de Modern: cantrips, remoción y dragones gigantes con Delve.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 4 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 2 },
      { cardName: 'Steam Vents', setCode: 'GRN', cardNumber: '257', amount: 4 },
      { cardName: 'Scalding Tarn', setCode: 'MH2', cardNumber: '254', amount: 4 },
      { cardName: 'Spirebluff Canal', setCode: 'OTJ', cardNumber: '270', amount: 4 },
      { cardName: 'Ragavan, Nimble Pilferer', setCode: 'MH2', cardNumber: '138', amount: 4 },
      { cardName: 'Dragon\'s Rage Channeler', setCode: 'MH2', cardNumber: '121', amount: 4 },
      { cardName: 'Murktide Regent', setCode: 'MH2', cardNumber: '52', amount: 4 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Counterspell', setCode: 'MH2', cardNumber: '267', amount: 4 },
      { cardName: 'Unholy Heat', setCode: 'MH2', cardNumber: '145', amount: 4 },
      { cardName: 'Expressive Iteration', setCode: 'STX', cardNumber: '186', amount: 4 },
      { cardName: 'Mishra\'s Bauble', setCode: '2XM', cardNumber: '274', amount: 4 },
      { cardName: 'Consider', setCode: 'MID', cardNumber: '44', amount: 4 },
      { cardName: 'Preordain', setCode: 'M11', cardNumber: '70', amount: 2 },
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Blood Moon', setCode: '2XM', cardNumber: '118', amount: 3 },
      { cardName: 'Flusterstorm', setCode: 'MH1', cardNumber: '255', amount: 3 },
      { cardName: 'Subtlety', setCode: 'MH2', cardNumber: '67', amount: 3 },
      { cardName: 'Brotherhood\'s End', setCode: 'BRO', cardNumber: '128', amount: 3 },
      { cardName: 'Unlicensed Hearse', setCode: 'SNC', cardNumber: '246', amount: 3 },
    ],
  },
  {
    id: 'meta-mod-burn',
    name: 'Mono Red Burn',
    format: 'Modern',
    archetype: 'Aggro',
    colors: ['R'],
    coverCard: { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
    description: '3 puntos de daño a la cabeza por cada maná gastado. Eficiencia pura e implacable.',
    tier: 'Tier 2',
    cards: [
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 20 },
      { cardName: 'Goblin Guide', setCode: '2XM', cardNumber: '127', amount: 4 },
      { cardName: 'Monastery Swiftspear', setCode: 'BRO', cardNumber: '144', amount: 4 },
      { cardName: 'Eidolon of the Great Revel', setCode: 'A25', cardNumber: '128', amount: 4 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Lava Spike', setCode: 'MMA', cardNumber: '121', amount: 4 },
      { cardName: 'Rift Bolt', setCode: 'IMA', cardNumber: '143', amount: 4 },
      { cardName: 'Skewer the Critics', setCode: 'RNA', cardNumber: '115', amount: 4 },
      { cardName: 'Searing Blaze', setCode: 'WWK', cardNumber: '90', amount: 4 },
      { cardName: 'Roiling Vortex', setCode: 'ZNR', cardNumber: '156', amount: 4 },
      { cardName: 'Skullcrack', setCode: 'GTC', cardNumber: '106', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Smash to Smithereens', setCode: 'ORI', cardNumber: '163', amount: 4 },
      { cardName: 'Deflecting Palm', setCode: 'KTK', cardNumber: '173', amount: 4 },
      { cardName: 'Kor Firewalker', setCode: 'WWK', cardNumber: '10', amount: 4 },
      { cardName: 'Sanctifier en-Vec', setCode: 'MH2', cardNumber: '27', amount: 3 },
    ],
  },
  {
    id: 'meta-mod-boros-energy',
    name: 'Boros Energy (MH3)',
    format: 'Modern',
    archetype: 'Aggro',
    colors: ['W', 'R'],
    coverCard: { cardName: 'Guide of Souls', setCode: 'MH3', cardNumber: '29', amount: 4 },
    description: 'La potencia energética de Modern Horizons 3: Ocelot Pride, Guide of Souls y Phlage.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 4 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 4 },
      { cardName: 'Sacred Foundry', setCode: 'GRN', cardNumber: '254', amount: 4 },
      { cardName: 'Arid Mesa', setCode: 'MH2', cardNumber: '244', amount: 4 },
      { cardName: 'Guide of Souls', setCode: 'MH3', cardNumber: '29', amount: 4 },
      { cardName: 'Ocelot Pride', setCode: 'MH3', cardNumber: '38', amount: 4 },
      { cardName: 'Amped Raptor', setCode: 'MH3', cardNumber: '114', amount: 4 },
      { cardName: 'Galvanic Discharge', setCode: 'MH3', cardNumber: '122', amount: 4 },
      { cardName: 'Phlage, Titan of Fire\'s Fury', setCode: 'MH3', cardNumber: '197', amount: 4 },
      { cardName: 'Ajani, Nacatl Pariah', setCode: 'MH3', cardNumber: '237', amount: 4 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Static Prison', setCode: 'MH3', cardNumber: '44', amount: 4 },
      { cardName: 'Inspiring Vantage', setCode: 'OTJ', cardNumber: '269', amount: 4 },
      { cardName: 'Sunbaked Canyon', setCode: 'MH1', cardNumber: '247', amount: 4 },
      { cardName: 'Wooded Foothills', setCode: 'KTK', cardNumber: '249', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Blood Moon', setCode: '2XM', cardNumber: '118', amount: 4 },
      { cardName: 'Wrath of the Skies', setCode: 'MH3', cardNumber: '49', amount: 4 },
      { cardName: 'Orim\'s Chant', setCode: 'MH3', cardNumber: '265', amount: 4 },
      { cardName: 'Chalice of the Void', setCode: 'A25', cardNumber: '222', amount: 3 },
    ],
  },
  {
    id: 'meta-mod-tron',
    name: 'Mono Green Tron',
    format: 'Modern',
    archetype: 'Ramp',
    colors: ['G'],
    coverCard: { cardName: 'Karn Liberated', setCode: '2XM', cardNumber: '1', amount: 4 },
    description: 'Junta Urza\'s Tower, Power Plant y Mine en turno 3 para bajar a Karn y Ulamog.',
    tier: 'Tier 1.5',
    cards: [
      { cardName: 'Urza\'s Tower', setCode: '2XM', cardNumber: '331', amount: 4 },
      { cardName: 'Urza\'s Power Plant', setCode: '2XM', cardNumber: '330', amount: 4 },
      { cardName: 'Urza\'s Mine', setCode: '2XM', cardNumber: '329', amount: 4 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 5 },
      { cardName: 'Boseiju, Who Endures', setCode: 'NEO', cardNumber: '266', amount: 2 },
      { cardName: 'Karn Liberated', setCode: '2XM', cardNumber: '1', amount: 4 },
      { cardName: 'Karn, the Great Creator', setCode: 'WAR', cardNumber: '1', amount: 4 },
      { cardName: 'Ulamog, the Ceaseless Hunger', setCode: 'BFZ', cardNumber: '15', amount: 2 },
      { cardName: 'Wurmcoil Engine', setCode: '2XM', cardNumber: '308', amount: 3 },
      { cardName: 'Expedition Map', setCode: '2XM', cardNumber: '255', amount: 4 },
      { cardName: 'Sylvan Scrying', setCode: 'BFZ', cardNumber: '192', amount: 4 },
      { cardName: 'Ancient Stirrings', setCode: '2XM', cardNumber: '151', amount: 4 },
      { cardName: 'Chromatic Star', setCode: '2XM', cardNumber: '242', amount: 4 },
      { cardName: 'Chromatic Sphere', setCode: '2XM', cardNumber: '241', amount: 4 },
      { cardName: 'Oblivion Stone', setCode: '2XM', cardNumber: '279', amount: 4 },
      { cardName: 'The One Ring', setCode: 'LTR', cardNumber: '246', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Sundering Titan', setCode: '2XM', cardNumber: '292', amount: 1 },
      { cardName: 'Ensnaring Bridge', setCode: '2XM', cardNumber: '253', amount: 1 },
      { cardName: 'Tormod\'s Crypt', setCode: 'M21', cardNumber: '241', amount: 2 },
      { cardName: 'Liquimetal Coating', setCode: 'SOM', cardNumber: '171', amount: 1 },
      { cardName: 'Chalice of the Void', setCode: 'A25', cardNumber: '222', amount: 2 },
      { cardName: 'Veil of Summer', setCode: 'M20', cardNumber: '198', amount: 4 },
      { cardName: 'Nature\'s Claim', setCode: 'IMA', cardNumber: '177', amount: 4 },
    ],
  },
  {
    id: 'meta-mod-yawgmoth',
    name: 'Golgari Yawgmoth',
    format: 'Modern',
    archetype: 'Combo',
    colors: ['B', 'G'],
    coverCard: { cardName: 'Yawgmoth, Thran Physician', setCode: 'MH1', cardNumber: '116', amount: 4 },
    description: 'Bucle infinito de contadores -1/-1 y Undying con Young Wolf y Blood Artist.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 4 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 4 },
      { cardName: 'Overgrown Tomb', setCode: 'GRN', cardNumber: '253', amount: 4 },
      { cardName: 'Verdant Catacombs', setCode: 'MH2', cardNumber: '260', amount: 4 },
      { cardName: 'Yawgmoth, Thran Physician', setCode: 'MH1', cardNumber: '116', amount: 4 },
      { cardName: 'Young Wolf', setCode: 'DKA', cardNumber: '134', amount: 4 },
      { cardName: 'Strangleroot Geist', setCode: 'DKA', cardNumber: '127', amount: 4 },
      { cardName: 'Grist, the Hunger Tide', setCode: 'MH2', cardNumber: '202', amount: 4 },
      { cardName: 'Chord of Calling', setCode: '2XM', cardNumber: '158', amount: 4 },
      { cardName: 'Eldritch Evolution', setCode: 'EMN', cardNumber: '155', amount: 4 },
      { cardName: 'Birds of Paradise', setCode: 'M12', cardNumber: '165', amount: 4 },
      { cardName: 'Delighted Halfling', setCode: 'LTR', cardNumber: '158', amount: 4 },
      { cardName: 'Blood Artist', setCode: 'EMA', cardNumber: '81', amount: 2 },
      { cardName: 'Orcish Bowmasters', setCode: 'LTR', cardNumber: '103', amount: 4 },
      { cardName: 'Boseiju, Who Endures', setCode: 'NEO', cardNumber: '266', amount: 2 },
      { cardName: 'Nurturing Peatland', setCode: 'MH1', cardNumber: '243', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Thoughtseize', setCode: '2XM', cardNumber: '109', amount: 4 },
      { cardName: 'Force of Vigor', setCode: 'MH1', cardNumber: '164', amount: 3 },
      { cardName: 'Fatal Push', setCode: '2XM', cardNumber: '93', amount: 4 },
      { cardName: 'Damping Sphere', setCode: 'DOM', cardNumber: '213', amount: 4 },
    ],
  },

  // =========================================================================
  // PIONEER
  // =========================================================================
  {
    id: 'meta-pio-rakdos-vamps',
    name: 'Rakdos Vampires',
    format: 'Pioneer',
    archetype: 'Midrange',
    colors: ['B', 'R'],
    coverCard: { cardName: 'Vein Ripper', setCode: 'MKM', cardNumber: '110', amount: 4 },
    description: 'Sorin baja a Vein Ripper en turno 3 para cerrar la partida con amenazas devastadoras.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 8 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 4 },
      { cardName: 'Blood Crypt', setCode: 'RNA', cardNumber: '245', amount: 4 },
      { cardName: 'Blackcleave Cliffs', setCode: 'ONE', cardNumber: '248', amount: 4 },
      { cardName: 'Sorin, Imperious Bloodlord', setCode: 'M20', cardNumber: '115', amount: 4 },
      { cardName: 'Vein Ripper', setCode: 'MKM', cardNumber: '110', amount: 4 },
      { cardName: 'Preacher of the Schism', setCode: 'LCI', cardNumber: '113', amount: 4 },
      { cardName: 'Fable of the Mirror-Breaker', setCode: 'NEO', cardNumber: '141', amount: 4 },
      { cardName: 'Thoughtseize', setCode: '2XM', cardNumber: '109', amount: 4 },
      { cardName: 'Fatal Push', setCode: '2XM', cardNumber: '93', amount: 4 },
      { cardName: 'Dusk Legion Zealot', setCode: 'RIX', cardNumber: '64', amount: 4 },
      { cardName: 'Bloodtithe Harvester', setCode: 'VOW', cardNumber: '232', amount: 4 },
      { cardName: 'Mutavault', setCode: 'M14', cardNumber: '228', amount: 4 },
      { cardName: 'Hive of the Eye Tyrant', setCode: 'AFR', cardNumber: '258', amount: 4 },
      { cardName: 'Den of the Bugbear', setCode: 'AFR', cardNumber: '254', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Duress', setCode: 'ONE', cardNumber: '92', amount: 4 },
      { cardName: 'Rending Volley', setCode: 'DTK', cardNumber: '150', amount: 4 },
      { cardName: 'Extinction Event', setCode: 'IKO', cardNumber: '88', amount: 4 },
      { cardName: 'Kolaghan\'s Command', setCode: 'DTK', cardNumber: '224', amount: 3 },
    ],
  },
  {
    id: 'meta-pio-izzet-phoenix',
    name: 'Izzet Phoenix',
    format: 'Pioneer',
    archetype: 'Combo',
    colors: ['U', 'R'],
    coverCard: { cardName: 'Arclight Phoenix', setCode: 'GRN', cardNumber: '91', amount: 4 },
    description: 'Lanza 3 hechizos por turno para revivir a tus Arclight Phoenix desde el cementerio.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 8 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 4 },
      { cardName: 'Steam Vents', setCode: 'GRN', cardNumber: '257', amount: 4 },
      { cardName: 'Spirebluff Canal', setCode: 'OTJ', cardNumber: '270', amount: 4 },
      { cardName: 'Arclight Phoenix', setCode: 'GRN', cardNumber: '91', amount: 4 },
      { cardName: 'Ledger Shredder', setCode: 'SNC', cardNumber: '46', amount: 4 },
      { cardName: 'Treasure Cruise', setCode: 'KTK', cardNumber: '59', amount: 4 },
      { cardName: 'Consider', setCode: 'MID', cardNumber: '44', amount: 4 },
      { cardName: 'Opt', setCode: 'XLN', cardNumber: '65', amount: 4 },
      { cardName: 'Fiery Impulse', setCode: 'ORI', cardNumber: '145', amount: 4 },
      { cardName: 'Lightning Axe', setCode: 'TSR', cardNumber: '174', amount: 4 },
      { cardName: 'Sleight of Hand', setCode: 'WOE', cardNumber: '67', amount: 4 },
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 4 },
      { cardName: 'Riverglide Pathway', setCode: 'ZNR', cardNumber: '264', amount: 4 },
      { cardName: 'Stormcarved Coast', setCode: 'VOW', cardNumber: '265', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Brotherhood\'s End', setCode: 'BRO', cardNumber: '128', amount: 4 },
      { cardName: 'Mystical Dispute', setCode: 'ELD', cardNumber: '58', amount: 4 },
      { cardName: 'Young Pyromancer', setCode: 'EMA', cardNumber: '155', amount: 4 },
      { cardName: 'Torch the Tower', setCode: 'WOE', cardNumber: '153', amount: 3 },
    ],
  },
  {
    id: 'meta-pio-mono-white-humans',
    name: 'Mono White Humans',
    format: 'Pioneer',
    archetype: 'Aggro',
    colors: ['W'],
    coverCard: { cardName: 'Adeline, Resplendent Cathar', setCode: 'MID', cardNumber: '1', amount: 4 },
    description: 'Ejército sinérgico de humanos con disrupción como Thalia y daño explosivo.',
    tier: 'Tier 1.5',
    cards: [
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 16 },
      { cardName: 'Mutavault', setCode: 'M14', cardNumber: '228', amount: 4 },
      { cardName: 'Castle Ardenvale', setCode: 'ELD', cardNumber: '238', amount: 2 },
      { cardName: 'Hopeful Initiate', setCode: 'VOW', cardNumber: '20', amount: 4 },
      { cardName: 'Dauntless Bodyguard', setCode: 'DOM', cardNumber: '14', amount: 4 },
      { cardName: 'Thalia, Guardian of Thraben', setCode: 'VOW', cardNumber: '38', amount: 4 },
      { cardName: 'Coppercoat Vanguard', setCode: 'MAT', cardNumber: '1', amount: 4 },
      { cardName: 'Adeline, Resplendent Cathar', setCode: 'MID', cardNumber: '1', amount: 4 },
      { cardName: 'Luminarch Aspirant', setCode: 'ZNR', cardNumber: '24', amount: 4 },
      { cardName: 'Brutal Cathar', setCode: 'MID', cardNumber: '7', amount: 4 },
      { cardName: 'Brave the Elements', setCode: 'M14', cardNumber: '10', amount: 4 },
      { cardName: 'Extraction Specialist', setCode: 'SNC', cardNumber: '12', amount: 4 },
      { cardName: 'Recruitment Officer', setCode: 'BRO', cardNumber: '23', amount: 2 },
    ],
    sideboard: [
      { cardName: 'Rest in Peace', setCode: 'A25', cardNumber: '28', amount: 4 },
      { cardName: 'Portable Hole', setCode: 'AFR', cardNumber: '33', amount: 4 },
      { cardName: 'Reidane, God of the Worthy', setCode: 'KHM', cardNumber: '21', amount: 4 },
      { cardName: 'Declaration in Stone', setCode: 'SOI', cardNumber: '12', amount: 3 },
    ],
  },
  {
    id: 'meta-pio-lotus-field',
    name: 'Lotus Field Combo',
    format: 'Pioneer',
    archetype: 'Combo',
    colors: ['U', 'G'],
    coverCard: { cardName: 'Lotus Field', setCode: 'M20', cardNumber: '249', amount: 4 },
    description: 'Copia Lotus Field con Thespian\'s Stage y endereza tus tierras para lanzar Approach of the Second Sun.',
    tier: 'Tier 1.5',
    cards: [
      { cardName: 'Lotus Field', setCode: 'M20', cardNumber: '249', amount: 4 },
      { cardName: 'Thespian\'s Stage', setCode: '2XM', cardNumber: '327', amount: 4 },
      { cardName: 'Botanical Sanctum', setCode: 'OTJ', cardNumber: '267', amount: 4 },
      { cardName: 'Yavimaya Coast', setCode: 'DMU', cardNumber: '261', amount: 4 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 4 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 4 },
      { cardName: 'Hidden Strings', setCode: 'DGM', cardNumber: '12', amount: 4 },
      { cardName: 'Pore Over the Pages', setCode: 'SOI', cardNumber: '79', amount: 4 },
      { cardName: 'Sylvan Scrying', setCode: 'BFZ', cardNumber: '192', amount: 4 },
      { cardName: 'Emergent Ultimatum', setCode: 'IKO', cardNumber: '185', amount: 4 },
      { cardName: 'Shimmer of Possibility', setCode: 'RNA', cardNumber: '51', amount: 4 },
      { cardName: 'Strategic Planning', setCode: 'KHM', cardNumber: '77', amount: 4 },
      { cardName: 'Approach of the Second Sun', setCode: 'AKH', cardNumber: '4', amount: 2 },
      { cardName: 'Omniscience', setCode: 'M19', cardNumber: '65', amount: 2 },
      { cardName: 'Peer into the Abyss', setCode: 'M21', cardNumber: '117', amount: 4 },
      { cardName: 'Boseiju, Who Endures', setCode: 'NEO', cardNumber: '266', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Thought Distortion', setCode: 'M20', cardNumber: '117', amount: 3 },
      { cardName: 'Chandra, Awakened Inferno', setCode: 'M20', cardNumber: '127', amount: 2 },
      { cardName: 'Void Snare', setCode: 'M15', cardNumber: '82', amount: 4 },
      { cardName: 'Nine Lives', setCode: 'M21', cardNumber: '28', amount: 3 },
      { cardName: 'Dragonlord Dromoka', setCode: 'DTK', cardNumber: '217', amount: 3 },
    ],
  },

  // =========================================================================
  // COMMANDER (EDH)
  // =========================================================================
  {
    id: 'meta-edh-atraxa',
    name: 'Atraxa: Superfriends Proliferate',
    format: 'Commander',
    archetype: 'Control',
    colors: ['W', 'U', 'B', 'G'],
    coverCard: { cardName: 'Atraxa, Praetors\' Voice', setCode: 'C16', cardNumber: '28', amount: 1 },
    description: 'Comandante legendaria de 4 colores: prolifera contadores de lealtad, +1/+1 y veneno cada turno.',
    tier: 'EDH Classic',
    cards: [
      { cardName: 'Atraxa, Praetors\' Voice', setCode: 'C16', cardNumber: '28', amount: 1 },
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 8 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 8 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 8 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 8 },
      { cardName: 'Command Tower', setCode: 'CMR', cardNumber: '350', amount: 1 },
      { cardName: 'Sol Ring', setCode: 'C16', cardNumber: '272', amount: 1 },
      { cardName: 'Arcane Signet', setCode: 'C20', cardNumber: '247', amount: 1 },
      { cardName: 'Doubling Season', setCode: '2XM', cardNumber: '164', amount: 1 },
      { cardName: 'Teferi, Hero of Dominaria', setCode: 'DOM', cardNumber: '207', amount: 1 },
      { cardName: 'Narset, Parter of Veils', setCode: 'WAR', cardNumber: '61', amount: 1 },
      { cardName: 'Oko, Thief of Crowns', setCode: 'ELD', cardNumber: '197', amount: 1 },
      { cardName: 'Vraska, Golgari Queen', setCode: 'GRN', cardNumber: '213', amount: 1 },
      { cardName: 'Karn Liberated', setCode: '2XM', cardNumber: '1', amount: 1 },
      { cardName: 'Ugin, the Spirit Dragon', setCode: 'M21', cardNumber: '1', amount: 1 },
      { cardName: 'Cyclonic Rift', setCode: 'RTR', cardNumber: '35', amount: 1 },
      { cardName: 'Demonic Tutor', setCode: 'UMA', cardNumber: '93', amount: 1 },
      { cardName: 'Vampiric Tutor', setCode: 'CMR', cardNumber: '156', amount: 1 },
      { cardName: 'Rhystic Study', setCode: 'JMP', cardNumber: '169', amount: 1 },
      { cardName: 'Smothering Tithe', setCode: 'RNA', cardNumber: '22', amount: 1 },
      { cardName: 'Heroic Intervention', setCode: 'M21', cardNumber: '188', amount: 1 },
      { cardName: 'Teferi\'s Protection', setCode: 'C17', cardNumber: '8', amount: 1 },
      { cardName: 'Evolution Sage', setCode: 'WAR', cardNumber: '159', amount: 1 },
      { cardName: 'Flux Channeler', setCode: 'WAR', cardNumber: '52', amount: 1 },
      { cardName: 'Deepglow Skate', setCode: 'C16', cardNumber: '7', amount: 1 },
      { cardName: 'Cultivate', setCode: 'M21', cardNumber: '177', amount: 1 },
      { cardName: 'Kodama\'s Reach', setCode: 'C20', cardNumber: '180', amount: 1 },
      { cardName: 'Farseek', setCode: 'M13', cardNumber: '170', amount: 1 },
      { cardName: 'Wrath of God', setCode: '2XM', cardNumber: '37', amount: 1 },
      { cardName: 'Damnation', setCode: 'MM3', cardNumber: '63', amount: 1 },
      { cardName: 'Toxic Deluge', setCode: '2XM', cardNumber: '110', amount: 1 },
      { cardName: 'Swords to Plowshares', setCode: 'A25', cardNumber: '35', amount: 1 },
      { cardName: 'Path to Exile', setCode: '2XM', cardNumber: '25', amount: 1 },
      { cardName: 'Assassin\'s Trophy', setCode: 'GRN', cardNumber: '152', amount: 1 },
      { cardName: 'Anguished Unmaking', setCode: 'SOI', cardNumber: '242', amount: 1 },
      { cardName: 'Overgrown Tomb', setCode: 'GRN', cardNumber: '253', amount: 1 },
      { cardName: 'Watery Grave', setCode: 'GRN', cardNumber: '259', amount: 1 },
      { cardName: 'Breeding Pool', setCode: 'RNA', cardNumber: '246', amount: 1 },
      { cardName: 'Godless Shrine', setCode: 'RNA', cardNumber: '248', amount: 1 },
      { cardName: 'Hallowed Fountain', setCode: 'RNA', cardNumber: '251', amount: 1 },
      { cardName: 'Temple Garden', setCode: 'GRN', cardNumber: '258', amount: 1 },
      { cardName: 'City of Brass', setCode: 'MMA', cardNumber: '221', amount: 1 },
      { cardName: 'Mana Confluence', setCode: 'JOU', cardNumber: '163', amount: 1 },
      { cardName: 'Fabled Passage', setCode: 'ELD', cardNumber: '244', amount: 1 },
      { cardName: 'Birds of Paradise', setCode: 'M12', cardNumber: '165', amount: 1 },
      { cardName: 'Noble Hierarch', setCode: '2XM', cardNumber: '177', amount: 1 },
      { cardName: 'Bloom Tender', setCode: 'EVE', cardNumber: '66', amount: 1 },
      { cardName: 'Lightning Greaves', setCode: '2XM', cardNumber: '267', amount: 1 },
      { cardName: 'Swiftfoot Boots', setCode: 'C20', cardNumber: '254', amount: 1 },
      { cardName: 'Counterspell', setCode: 'MH2', cardNumber: '267', amount: 1 },
      { cardName: 'Swan Song', setCode: 'C16', cardNumber: '98', amount: 1 },
      { cardName: 'Fierce Guardianship', setCode: 'C20', cardNumber: '35', amount: 1 },
      { cardName: 'Force of Will', setCode: '2XM', cardNumber: '51', amount: 1 },
      { cardName: 'Pact of Negation', setCode: 'A25', cardNumber: '68', amount: 1 },
      { cardName: 'The Great Henge', setCode: 'ELD', cardNumber: '161', amount: 1 },
      { cardName: 'Esper Sentinel', setCode: 'MH2', cardNumber: '12', amount: 1 },
    ],
    sideboard: [],
  },
  {
    id: 'meta-edh-krenko',
    name: 'Krenko: Goblin Mob Army',
    format: 'Commander',
    archetype: 'Tribal',
    colors: ['R'],
    coverCard: { cardName: 'Krenko, Mob Boss', setCode: 'M13', cardNumber: '138', amount: 1 },
    description: 'Genera un ejército exponencial de trasgos y arrolla la mesa en pocos turnos.',
    tier: 'EDH Classic',
    cards: [
      { cardName: 'Krenko, Mob Boss', setCode: 'M13', cardNumber: '138', amount: 1 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 36 },
      { cardName: 'Sol Ring', setCode: 'C16', cardNumber: '272', amount: 1 },
      { cardName: 'Arcane Signet', setCode: 'C20', cardNumber: '247', amount: 1 },
      { cardName: 'Ruby Medallion', setCode: 'C14', cardNumber: '265', amount: 1 },
      { cardName: 'Goblin Chieftain', setCode: 'M12', cardNumber: '138', amount: 1 },
      { cardName: 'Goblin King', setCode: '10E', cardNumber: '207', amount: 1 },
      { cardName: 'Goblin Warchief', setCode: 'DOM', cardNumber: '130', amount: 1 },
      { cardName: 'Skirk Prospector', setCode: 'DOM', cardNumber: '144', amount: 1 },
      { cardName: 'Goblin Matron', setCode: 'MH1', cardNumber: '129', amount: 1 },
      { cardName: 'Goblin Recruiter', setCode: '6ED', cardNumber: '186', amount: 1 },
      { cardName: 'Goblin Ringleader', setCode: 'M20', cardNumber: '143', amount: 1 },
      { cardName: 'Goblin Piledriver', setCode: 'ORI', cardNumber: '151', amount: 1 },
      { cardName: 'Goblin Bushwhacker', setCode: 'ZEN', cardNumber: '125', amount: 1 },
      { cardName: 'Reckless Bushwhacker', setCode: 'OGW', cardNumber: '116', amount: 1 },
      { cardName: 'Siege-Gang Commander', setCode: 'DOM', cardNumber: '143', amount: 1 },
      { cardName: 'Pashalik Mons', setCode: 'MH1', cardNumber: '138', amount: 1 },
      { cardName: 'Muxus, Goblin Grandee', setCode: 'JMP', cardNumber: '24', amount: 1 },
      { cardName: 'Krenko, Tin Street Kingpin', setCode: 'WAR', cardNumber: '137', amount: 1 },
      { cardName: 'Impact Tremors', setCode: 'DTK', cardNumber: '140', amount: 1 },
      { cardName: 'Purphoros, God of the Forge', setCode: 'THS', cardNumber: '135', amount: 1 },
      { cardName: 'Shared Animosity', setCode: 'E01', cardNumber: '58', amount: 1 },
      { cardName: 'Coat of Arms', setCode: 'M10', cardNumber: '207', amount: 1 },
      { cardName: 'Skullclamp', setCode: 'C20', cardNumber: '251', amount: 1 },
      { cardName: 'Lightning Greaves', setCode: '2XM', cardNumber: '267', amount: 1 },
      { cardName: 'Swiftfoot Boots', setCode: 'C20', cardNumber: '254', amount: 1 },
      { cardName: 'Thousand-Year Elixir', setCode: 'C13', cardNumber: '266', amount: 1 },
      { cardName: 'Illusionist\'s Bracers', setCode: 'GTC', cardNumber: '231', amount: 1 },
      { cardName: 'Chaos Warp', setCode: 'C20', cardNumber: '146', amount: 1 },
      { cardName: 'Blasphemous Act', setCode: 'C20', cardNumber: '141', amount: 1 },
      { cardName: 'Vandalblast', setCode: 'C15', cardNumber: '170', amount: 1 },
      { cardName: 'Faithless Looting', setCode: 'UMA', cardNumber: '128', amount: 1 },
      { cardName: 'Wheel of Misfortune', setCode: 'CMR', cardNumber: '211', amount: 1 },
      { cardName: 'Jeska\'s Will', setCode: 'CMR', cardNumber: '187', amount: 1 },
      { cardName: 'Deflecting Swat', setCode: 'C20', cardNumber: '50', amount: 1 },
      { cardName: 'Tibalt\'s Trickery', setCode: 'KHM', cardNumber: '153', amount: 1 },
      { cardName: 'Blood Moon', setCode: '2XM', cardNumber: '118', amount: 1 },
      { cardName: 'Castle Embereth', setCode: 'ELD', cardNumber: '239', amount: 1 },
      { cardName: 'War Room', setCode: 'CMR', cardNumber: '361', amount: 1 },
      { cardName: 'Nykthos, Shrine to Nyx', setCode: 'THS', cardNumber: '223', amount: 1 },
    ],
    sideboard: [],
  },
  {
    id: 'meta-edh-edgar',
    name: 'Edgar Markov: Vampire Aristocrats',
    format: 'Commander',
    archetype: 'Tribal',
    colors: ['W', 'B', 'R'],
    coverCard: { cardName: 'Edgar Markov', setCode: 'C17', cardNumber: '36', amount: 1 },
    description: 'Eminence genera tokens de vampiro gratis cada vez que lanzas un hechizo de vampiro.',
    tier: 'EDH Classic',
    cards: [
      { cardName: 'Edgar Markov', setCode: 'C17', cardNumber: '36', amount: 1 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 12 },
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 8 },
      { cardName: 'Plains', setCode: 'LEA', cardNumber: '286', amount: 8 },
      { cardName: 'Command Tower', setCode: 'CMR', cardNumber: '350', amount: 1 },
      { cardName: 'Sol Ring', setCode: 'C16', cardNumber: '272', amount: 1 },
      { cardName: 'Arcane Signet', setCode: 'C20', cardNumber: '247', amount: 1 },
      { cardName: 'Bloodline Keeper', setCode: 'ISD', cardNumber: '90', amount: 1 },
      { cardName: 'Captivating Vampire', setCode: 'M11', cardNumber: '87', amount: 1 },
      { cardName: 'Cordial Vampire', setCode: 'MH1', cardNumber: '83', amount: 1 },
      { cardName: 'Knight of the Ebon Legion', setCode: 'M20', cardNumber: '105', amount: 1 },
      { cardName: 'Vampire Nighthawk', setCode: 'M13', cardNumber: '112', amount: 1 },
      { cardName: 'Dusk Legion Zealot', setCode: 'RIX', cardNumber: '64', amount: 1 },
      { cardName: 'Cruel Celebrant', setCode: 'WAR', cardNumber: '188', amount: 1 },
      { cardName: 'Elenda, the Dusk Rose', setCode: 'RIX', cardNumber: '157', amount: 1 },
      { cardName: 'Patron of the Vein', setCode: 'C17', cardNumber: '20', amount: 1 },
      { cardName: 'Anowon, the Ruin Sage', setCode: 'WWK', cardNumber: '49', amount: 1 },
      { cardName: 'Skullclamp', setCode: 'C20', cardNumber: '251', amount: 1 },
      { cardName: 'Phyrexian Arena', setCode: '8ED', cardNumber: '152', amount: 1 },
      { cardName: 'Necropotence', setCode: 'IMA', cardNumber: '98', amount: 1 },
      { cardName: 'Toxic Deluge', setCode: '2XM', cardNumber: '110', amount: 1 },
      { cardName: 'Anguished Unmaking', setCode: 'SOI', cardNumber: '242', amount: 1 },
      { cardName: 'Boros Charm', setCode: 'FDN', cardNumber: '721', amount: 1 },
      { cardName: 'Teferi\'s Protection', setCode: 'C17', cardNumber: '8', amount: 1 },
      { cardName: 'Blood Crypt', setCode: 'RNA', cardNumber: '245', amount: 1 },
      { cardName: 'Godless Shrine', setCode: 'RNA', cardNumber: '248', amount: 1 },
      { cardName: 'Sacred Foundry', setCode: 'GRN', cardNumber: '254', amount: 1 },
      { cardName: 'Savai Triome', setCode: 'IKO', cardNumber: '253', amount: 1 },
    ],
    sideboard: [],
  },

  // =========================================================================
  // PAUPER
  // =========================================================================
  {
    id: 'meta-pau-kuldotha-red',
    name: 'Kuldotha Red',
    format: 'Pauper',
    archetype: 'Aggro',
    colors: ['R'],
    coverCard: { cardName: 'Kuldotha Rebirth', setCode: 'SOM', cardNumber: '96', amount: 4 },
    description: 'El arquetipo rey de Pauper: artefactos sacrificables y oleadas de tokens 1/1 con quemadura.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 14 },
      { cardName: 'Great Furnace', setCode: 'MRD', cardNumber: '282', amount: 4 },
      { cardName: 'Monastery Swiftspear', setCode: 'BRO', cardNumber: '144', amount: 4 },
      { cardName: 'Goblin Bushwhacker', setCode: 'ZEN', cardNumber: '125', amount: 4 },
      { cardName: 'Kuldotha Rebirth', setCode: 'SOM', cardNumber: '96', amount: 4 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Galvanic Blast', setCode: 'SOM', cardNumber: '91', amount: 4 },
      { cardName: 'Chain Lightning', setCode: 'EMA', cardNumber: '123', amount: 4 },
      { cardName: 'Voldaren Epicure', setCode: 'VOW', cardNumber: '182', amount: 4 },
      { cardName: 'Synthesizer Experimental', setCode: 'NEO', cardNumber: '138', amount: 4 },
      { cardName: 'Reckless Lackey', setCode: 'OTJ', cardNumber: '140', amount: 4 },
      { cardName: 'Goblin Tomb Raider', setCode: 'LCI', cardNumber: '146', amount: 4 },
      { cardName: 'Lava Dart', setCode: 'MH1', cardNumber: '134', amount: 2 },
    ],
    sideboard: [
      { cardName: 'Smash to Smithereens', setCode: 'ORI', cardNumber: '163', amount: 4 },
      { cardName: 'Flaring Pain', setCode: 'JUD', cardNumber: '89', amount: 4 },
      { cardName: 'Red Elemental Blast', setCode: '4ED', cardNumber: '218', amount: 4 },
      { cardName: 'End the Festivities', setCode: 'VOW', cardNumber: '155', amount: 3 },
    ],
  },
  {
    id: 'meta-pau-mono-blue-terror',
    name: 'Mono Blue Terror',
    format: 'Pauper',
    archetype: 'Midrange',
    colors: ['U'],
    coverCard: { cardName: 'Tolarian Terror', setCode: 'DMU', cardNumber: '72', amount: 4 },
    description: 'Llena el cementerio con cantrips baratos y baja 5/5 con Ward 2 por solo 1 maná azul.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 16 },
      { cardName: 'Tolarian Terror', setCode: 'DMU', cardNumber: '72', amount: 4 },
      { cardName: 'Cryptic Serpent', setCode: 'AKH', cardNumber: '48', amount: 4 },
      { cardName: 'Delver of Secrets', setCode: 'ISD', cardNumber: '51', amount: 4 },
      { cardName: 'Thought Scour', setCode: 'IMA', cardNumber: '76', amount: 4 },
      { cardName: 'Mental Note', setCode: 'JUD', cardNumber: '46', amount: 4 },
      { cardName: 'Brainstorm', setCode: 'EMA', cardNumber: '40', amount: 4 },
      { cardName: 'Consider', setCode: 'MID', cardNumber: '44', amount: 4 },
      { cardName: 'Counterspell', setCode: 'MH2', cardNumber: '267', amount: 4 },
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 4 },
      { cardName: 'Snap', setCode: 'DDS', cardNumber: '10', amount: 4 },
      { cardName: 'Deep Analysis', setCode: 'EMA', cardNumber: '45', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Blue Elemental Blast', setCode: '4ED', cardNumber: '63', amount: 4 },
      { cardName: 'Hydroblast', setCode: 'EMA', cardNumber: '55', amount: 4 },
      { cardName: 'Annul', setCode: 'KHM', cardNumber: '42', amount: 4 },
      { cardName: 'Gut Shot', setCode: 'MM2', cardNumber: '117', amount: 3 },
    ],
  },
  {
    id: 'meta-pau-affinity',
    name: 'Grixis Affinity',
    format: 'Pauper',
    archetype: 'Midrange',
    colors: ['U', 'B', 'R'],
    coverCard: { cardName: 'Myr Enforcer', setCode: 'MM2', cardNumber: '225', amount: 4 },
    description: 'Tierras artefacto indestructibles, robo masivo de cartas y criaturas 4/4 gratuitas.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Seat of the Synod', setCode: 'MRD', cardNumber: '283', amount: 4 },
      { cardName: 'Vault of Whispers', setCode: 'MRD', cardNumber: '286', amount: 4 },
      { cardName: 'Great Furnace', setCode: 'MRD', cardNumber: '282', amount: 4 },
      { cardName: 'Drossforge Bridge', setCode: 'MH2', cardNumber: '246', amount: 4 },
      { cardName: 'Silverbluff Bridge', setCode: 'MH2', cardNumber: '255', amount: 4 },
      { cardName: 'Mistvault Bridge', setCode: 'MH2', cardNumber: '249', amount: 4 },
      { cardName: 'Myr Enforcer', setCode: 'MM2', cardNumber: '225', amount: 4 },
      { cardName: 'Frogmite', setCode: 'MM2', cardNumber: '215', amount: 4 },
      { cardName: 'Thoughtcast', setCode: 'MM2', cardNumber: '64', amount: 4 },
      { cardName: 'Deadly Dispute', setCode: 'AFR', cardNumber: '94', amount: 4 },
      { cardName: 'Galvanic Blast', setCode: 'SOM', cardNumber: '91', amount: 4 },
      { cardName: 'Cast Down', setCode: 'DOM', cardNumber: '81', amount: 4 },
      { cardName: 'Blood Fountain', setCode: 'VOW', cardNumber: '95', amount: 4 },
      { cardName: 'Metallic Rebuke', setCode: 'AER', cardNumber: '39', amount: 4 },
      { cardName: 'Ichor Wellspring', setCode: '2XM', cardNumber: '261', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Pyroblast', setCode: 'EMA', cardNumber: '142', amount: 4 },
      { cardName: 'Hydroblast', setCode: 'EMA', cardNumber: '55', amount: 4 },
      { cardName: 'Nihil Spellbomb', setCode: 'A25', cardNumber: '226', amount: 4 },
      { cardName: 'Krark-Clan Shaman', setCode: 'MRD', cardNumber: '98', amount: 3 },
    ],
  },

  // =========================================================================
  // LEGACY
  // =========================================================================
  {
    id: 'meta-leg-grixis-delver',
    name: 'Grixis Delver',
    format: 'Legacy',
    archetype: 'Midrange',
    colors: ['U', 'B', 'R'],
    coverCard: { cardName: 'Delver of Secrets', setCode: 'ISD', cardNumber: '51', amount: 4 },
    description: 'El arquetipo definitivo de Legacy: Force of Will, Wasteland, Daze y Brainstorm.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Volcanic Island', setCode: 'LEA', cardNumber: '291', amount: 4 },
      { cardName: 'Underground Sea', setCode: 'LEA', cardNumber: '289', amount: 4 },
      { cardName: 'Wasteland', setCode: 'EMA', cardNumber: '248', amount: 4 },
      { cardName: 'Polluted Delta', setCode: 'KTK', cardNumber: '239', amount: 4 },
      { cardName: 'Scalding Tarn', setCode: 'MH2', cardNumber: '254', amount: 4 },
      { cardName: 'Delver of Secrets', setCode: 'ISD', cardNumber: '51', amount: 4 },
      { cardName: 'Dragon\'s Rage Channeler', setCode: 'MH2', cardNumber: '121', amount: 4 },
      { cardName: 'Murktide Regent', setCode: 'MH2', cardNumber: '52', amount: 4 },
      { cardName: 'Orcish Bowmasters', setCode: 'LTR', cardNumber: '103', amount: 4 },
      { cardName: 'Brainstorm', setCode: 'EMA', cardNumber: '40', amount: 4 },
      { cardName: 'Ponder', setCode: 'M12', cardNumber: '73', amount: 4 },
      { cardName: 'Force of Will', setCode: '2XM', cardNumber: '51', amount: 4 },
      { cardName: 'Daze', setCode: 'EMA', cardNumber: '44', amount: 4 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Mishra\'s Bauble', setCode: '2XM', cardNumber: '274', amount: 4 },
      { cardName: 'Snuff Out', setCode: 'MMQ', cardNumber: '162', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Red Elemental Blast', setCode: '4ED', cardNumber: '218', amount: 4 },
      { cardName: 'Pyroblast', setCode: 'EMA', cardNumber: '142', amount: 4 },
      { cardName: 'Surgical Extraction', setCode: '2XM', cardNumber: '108', amount: 4 },
      { cardName: 'Null Rod', setCode: 'WTH', cardNumber: '154', amount: 3 },
    ],
  },
  {
    id: 'meta-leg-reanimator',
    name: 'BR Reanimator',
    format: 'Legacy',
    archetype: 'Combo',
    colors: ['B', 'R'],
    coverCard: { cardName: 'Griselbrand', setCode: 'MM3', cardNumber: '72', amount: 4 },
    description: 'Entomb en turno 1 para enterrar a Griselbrand o Archon of Cruelty y revivirlo con Reanimate.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Badlands', setCode: 'LEA', cardNumber: '284', amount: 4 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 4 },
      { cardName: 'Bloodstained Mire', setCode: 'KTK', cardNumber: '230', amount: 4 },
      { cardName: 'Griselbrand', setCode: 'MM3', cardNumber: '72', amount: 4 },
      { cardName: 'Archon of Cruelty', setCode: 'MH2', cardNumber: '75', amount: 4 },
      { cardName: 'Entomb', setCode: 'EMA', cardNumber: '87', amount: 4 },
      { cardName: 'Reanimate', setCode: 'UMA', cardNumber: '110', amount: 4 },
      { cardName: 'Exhume', setCode: 'USG', cardNumber: '134', amount: 4 },
      { cardName: 'Animate Dead', setCode: 'EMA', cardNumber: '78', amount: 4 },
      { cardName: 'Dark Ritual', setCode: 'A25', cardNumber: '82', amount: 4 },
      { cardName: 'Lotus Petal', setCode: 'TMP', cardNumber: '294', amount: 4 },
      { cardName: 'Faithless Looting', setCode: 'UMA', cardNumber: '128', amount: 4 },
      { cardName: 'Thoughtseize', setCode: '2XM', cardNumber: '109', amount: 4 },
      { cardName: 'Unmask', setCode: 'MMQ', cardNumber: '168', amount: 4 },
      { cardName: 'Dauthi Voidwalker', setCode: 'MH2', cardNumber: '81', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Serenity', setCode: 'WTH', cardNumber: '24', amount: 4 },
      { cardName: 'Abrade', setCode: 'HOU', cardNumber: '83', amount: 4 },
      { cardName: 'Show and Tell', setCode: 'USG', cardNumber: '96', amount: 4 },
      { cardName: 'Magus of the Moon', setCode: 'IMA', cardNumber: '138', amount: 3 },
    ],
  },

  // =========================================================================
  // VINTAGE
  // =========================================================================
  {
    id: 'meta-vin-paradoxical',
    name: 'Paradoxical Outcome (Power 9)',
    format: 'Vintage',
    archetype: 'Combo',
    colors: ['U'],
    coverCard: { cardName: 'Black Lotus', setCode: 'LEA', cardNumber: '232', amount: 1 },
    description: 'Juega el Power Nine completo: Black Lotus, Moxes, Time Walk y Outcome para robar todo el mazo.',
    tier: 'Vintage Tier 1',
    cards: [
      { cardName: 'Black Lotus', setCode: 'LEA', cardNumber: '232', amount: 1 },
      { cardName: 'Mox Sapphire', setCode: 'LEA', cardNumber: '265', amount: 1 },
      { cardName: 'Mox Jet', setCode: 'LEA', cardNumber: '263', amount: 1 },
      { cardName: 'Mox Ruby', setCode: 'LEA', cardNumber: '264', amount: 1 },
      { cardName: 'Mox Emerald', setCode: 'LEA', cardNumber: '262', amount: 1 },
      { cardName: 'Mox Pearl', setCode: 'LEA', cardNumber: '266', amount: 1 },
      { cardName: 'Time Walk', setCode: 'LEA', cardNumber: '84', amount: 1 },
      { cardName: 'Ancestral Recall', setCode: 'LEA', cardNumber: '47', amount: 1 },
      { cardName: 'Sol Ring', setCode: 'C16', cardNumber: '272', amount: 1 },
      { cardName: 'Mana Crypt', setCode: '2XM', cardNumber: '270', amount: 1 },
      { cardName: 'Mana Vault', setCode: '2XM', cardNumber: '271', amount: 1 },
      { cardName: 'Paradoxical Outcome', setCode: 'KLD', cardNumber: '60', amount: 4 },
      { cardName: 'Force of Will', setCode: '2XM', cardNumber: '51', amount: 4 },
      { cardName: 'Force of Negation', setCode: 'MH1', cardNumber: '52', amount: 4 },
      { cardName: 'Brainstorm', setCode: 'EMA', cardNumber: '40', amount: 1 },
      { cardName: 'Ponder', setCode: 'M12', cardNumber: '73', amount: 1 },
      { cardName: 'Gitaxian Probe', setCode: 'NPH', cardNumber: '35', amount: 1 },
      { cardName: 'Merchant Scroll', setCode: '8ED', cardNumber: '91', amount: 1 },
      { cardName: 'Mystical Tutor', setCode: 'EMA', cardNumber: '62', amount: 1 },
      { cardName: 'Tinker', setCode: 'ULG', cardNumber: '45', amount: 1 },
      { cardName: 'Bolas\'s Citadel', setCode: 'WAR', cardNumber: '79', amount: 1 },
      { cardName: 'Sensei\'s Divining Top', setCode: 'EMA', cardNumber: '231', amount: 1 },
      { cardName: 'Monastery Mentor', setCode: 'FRF', cardNumber: '20', amount: 2 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 8 },
      { cardName: 'Tolarian Academy', setCode: 'USG', cardNumber: '330', amount: 1 },
      { cardName: 'Urza\'s Saga', setCode: 'MH2', cardNumber: '259', amount: 4 },
      { cardName: 'Polluted Delta', setCode: 'KTK', cardNumber: '239', amount: 4 },
      { cardName: 'Scalding Tarn', setCode: 'MH2', cardNumber: '254', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Flusterstorm', setCode: 'MH1', cardNumber: '255', amount: 4 },
      { cardName: 'Mindbreak Trap', setCode: 'ZEN', cardNumber: '57', amount: 4 },
      { cardName: 'Hurkyl\'s Recall', setCode: '10E', cardNumber: '88', amount: 4 },
      { cardName: 'Tormod\'s Crypt', setCode: 'M21', cardNumber: '241', amount: 3 },
    ],
  },

  // =========================================================================
  // TIMELESS & HISTORIC
  // =========================================================================
  {
    id: 'meta-tim-show-tell',
    name: 'Show and Tell (Timeless)',
    format: 'Timeless',
    archetype: 'Combo',
    colors: ['U', 'G'],
    coverCard: { cardName: 'Show and Tell', setCode: 'USG', cardNumber: '96', amount: 4 },
    description: 'Lanza Show and Tell en turno 3 para bajar Omniscience y jugar Atraxa gratis.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Show and Tell', setCode: 'USG', cardNumber: '96', amount: 4 },
      { cardName: 'Omniscience', setCode: 'M19', cardNumber: '65', amount: 4 },
      { cardName: 'Atraxa, Grand Unifier', setCode: 'ONE', cardNumber: '196', amount: 4 },
      { cardName: 'Brainstorm', setCode: 'EMA', cardNumber: '40', amount: 4 },
      { cardName: 'Dark Ritual', setCode: 'A25', cardNumber: '82', amount: 4 },
      { cardName: 'Thoughtseize', setCode: '2XM', cardNumber: '109', amount: 4 },
      { cardName: 'Demonic Tutor', setCode: 'UMA', cardNumber: '93', amount: 1 },
      { cardName: 'Vampiric Tutor', setCode: 'CMR', cardNumber: '156', amount: 1 },
      { cardName: 'Veil of Summer', setCode: 'M20', cardNumber: '198', amount: 4 },
      { cardName: 'Polluted Delta', setCode: 'KTK', cardNumber: '239', amount: 4 },
      { cardName: 'Watery Grave', setCode: 'GRN', cardNumber: '259', amount: 4 },
      { cardName: 'Overgrown Tomb', setCode: 'GRN', cardNumber: '253', amount: 4 },
      { cardName: 'Breeding Pool', setCode: 'RNA', cardNumber: '246', amount: 4 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 6 },
      { cardName: 'Swamp', setCode: 'LEA', cardNumber: '290', amount: 4 },
      { cardName: 'Forest', setCode: 'LEA', cardNumber: '294', amount: 4 },
    ],
    sideboard: [
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 4 },
      { cardName: 'Fatal Push', setCode: '2XM', cardNumber: '93', amount: 4 },
      { cardName: 'Leyline of Sanctity', setCode: 'M20', cardNumber: '26', amount: 4 },
      { cardName: 'Boseiju, Who Endures', setCode: 'NEO', cardNumber: '266', amount: 3 },
    ],
  },
  {
    id: 'meta-his-wizards',
    name: 'Izzet Wizards (Historic)',
    format: 'Historic',
    archetype: 'Aggro',
    colors: ['U', 'R'],
    coverCard: { cardName: 'Symmetry Sage', setCode: 'STX', cardNumber: '56', amount: 4 },
    description: 'Symmetry Sage convierte a tus magos en 3/3 voladores y Dreadhorde Arcanist relanza hechizos gratis.',
    tier: 'Tier 1',
    cards: [
      { cardName: 'Mountain', setCode: 'LEA', cardNumber: '292', amount: 6 },
      { cardName: 'Island', setCode: 'LEA', cardNumber: '288', amount: 6 },
      { cardName: 'Steam Vents', setCode: 'GRN', cardNumber: '257', amount: 4 },
      { cardName: 'Spirebluff Canal', setCode: 'OTJ', cardNumber: '270', amount: 4 },
      { cardName: 'Symmetry Sage', setCode: 'STX', cardNumber: '56', amount: 4 },
      { cardName: 'Soul-Scar Mage', setCode: 'AKH', cardNumber: '148', amount: 4 },
      { cardName: 'Dreadhorde Arcanist', setCode: 'WAR', cardNumber: '125', amount: 4 },
      { cardName: 'Arcanist\'s Owl', setCode: 'ELD', cardNumber: '206', amount: 2 },
      { cardName: 'Lightning Bolt', setCode: 'M10', cardNumber: '146', amount: 4 },
      { cardName: 'Expressive Iteration', setCode: 'STX', cardNumber: '186', amount: 4 },
      { cardName: 'Consider', setCode: 'MID', cardNumber: '44', amount: 4 },
      { cardName: 'Play with Fire', setCode: 'MID', cardNumber: '154', amount: 4 },
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 4 },
      { cardName: 'Mishra\'s Bauble', setCode: '2XM', cardNumber: '274', amount: 4 },
      { cardName: 'Riverglide Pathway', setCode: 'ZNR', cardNumber: '264', amount: 2 },
    ],
    sideboard: [
      { cardName: 'Spell Pierce', setCode: 'NEO', cardNumber: '80', amount: 2 },
      { cardName: 'Brotherhood\'s End', setCode: 'BRO', cardNumber: '128', amount: 3 },
      { cardName: 'Unlicensed Hearse', setCode: 'SNC', cardNumber: '246', amount: 3 },
      { cardName: 'Roiling Vortex', setCode: 'ZNR', cardNumber: '156', amount: 3 },
      { cardName: 'Flame Blessed Bolt', setCode: 'VOW', cardNumber: '158', amount: 4 },
    ],
  },
]
