export type HintKind = 'rules' | 'hint' | 'icon' | 'info'
export type HintStatus = 'rendered' | 'known-unrendered'

export interface HintRegistryRow {
  id: string
  kind: HintKind
  status: HintStatus
  ref?: string
  causa?: string
}

export const hintRegistry: HintRegistryRow[] = [
  { id: "rules:Can't attack{addSourceObjectName(game, ability)}", kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: "rules:Can't block{addSourceObjectName(game, ability)}", kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: "rules:Can't transform{addSourceObjectName(game, ability)}", kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: "rules:Can't untapped{addSourceObjectName(game, ability)}", kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: "rules:Can't use activated abilities{addSourceObjectName(game, ability)}", kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Goaded by {player.getLogName()} (must attack)', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must attack defender {object.getLogName()}{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must attack defender {player.getLogName()}{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must attack{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must block all attackers{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must block any{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must block attacker if able {object.getLogName()}{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must block attacker {object.getLogName()}{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'rules:Must block{addSourceObjectName(game, ability)}', kind: 'rules', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'hint:ConditionHint', kind: 'hint', status: 'known-unrendered', causa: 'contenedor genérico; su texto solo aparece como línea de reglas' },
  { id: 'hint:ConditionTrueHint', kind: 'hint', status: 'known-unrendered', causa: 'contenedor genérico; su texto solo aparece como línea de reglas' },
  { id: 'hint:StaticHint', kind: 'hint', status: 'known-unrendered', causa: 'texto estático; visible solo como línea de reglas' },
  { id: 'hint:ValueConditionHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (línea de reglas)' },
  { id: 'hint:ValueHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador/valor en línea de reglas)' },
  { id: 'hint:ValuePositiveHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (línea de reglas)' },
  { id: 'hint:AbilityResolutionCountHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:ArtifactYouControlHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:BargainCostWasPaidHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (coste pagado)' },
  { id: 'hint:BoastHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:CanPlayAdditionalLandsHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (las tierras jugables ya se resaltan)' },
  { id: 'hint:CaseSolvedHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:43' },
  { id: 'hint:CitysBlessingHint', kind: 'hint', status: 'known-unrendered', causa: 'cubierto vía designationNames (MechanicsTray.tsx:155); el hint no se parsea (D2)' },
  { id: 'hint:ClassLevelHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:35' },
  { id: 'hint:ConditionPermanentHint', kind: 'hint', status: 'known-unrendered', causa: 'contenedor genérico; su texto solo aparece como línea de reglas' },
  { id: 'hint:ControlACommanderHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (línea de reglas)' },
  { id: 'hint:ControlArtifactAndEnchantmentHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (línea de reglas)' },
  { id: 'hint:ControllerDiscardedHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (línea de reglas)' },
  { id: 'hint:CountersOnPermanentsHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:CovenHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:CreaturesDiedThisTurnHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:CreaturesYouControlHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:CurrentDungeonHint', kind: 'hint', status: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:103' },
  { id: 'hint:DayNightHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/dayNight.ts:12' },
  { id: 'hint:DifferentManaValuesInGraveHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:DomainHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:EnduringStoryHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:EvidenceHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:45' },
  { id: 'hint:FerociousHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:GatesYouControlHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:HarnessedHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:44' },
  { id: 'hint:InitiativeHint', kind: 'hint', status: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:153' },
  { id: 'hint:LandsYouControlHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:MetalcraftHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:ModesAlreadyUsedHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (modos usados)' },
  { id: 'hint:MonarchHint', kind: 'hint', status: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:152' },
  { id: 'hint:MonstrousHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:30' },
  { id: 'hint:MorbidHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:MyTurnHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (condición de turno)' },
  { id: 'hint:NotMyTurnHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (condición de turno)' },
  { id: 'hint:OpenSideboardHint', kind: 'hint', status: 'known-unrendered', causa: 'la UI de sideboard es genérica; no parsea este hint' },
  { id: 'hint:OpponentsLostLifeHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (condición)' },
  { id: 'hint:OpponentsTurnHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (condición de turno)' },
  { id: 'hint:PartyCountHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:PermanentsYouControlHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:PlayersLeftRightHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (orden de jugadores)' },
  { id: 'hint:ProwlCostWasPaidHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (coste pagado)' },
  { id: 'hint:ProwlHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:RaidHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:RenownedHint', kind: 'hint', status: 'rendered', ref: 'web/src/board/designations.ts:30' },
  { id: 'hint:TeamworkCostWasPaidHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (coste pagado)' },
  { id: 'hint:CardTypesInGraveyardHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:CardsInOpponentGraveyardConditionHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:ColorsAmongControlledPermanentsHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:DesertControlledOrGraveyardHint', kind: 'hint', status: 'known-unrendered', causa: 'condición de arquetipo sin badge (D2)' },
  { id: 'hint:EllywickTumblestrumEmblemHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (emblema)' },
  { id: 'hint:MutateCountHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:OnceEachTurnCastHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador)' },
  { id: 'hint:RegenerationShieldsHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (escudos de regeneración)' },
  { id: 'hint:VolosJournalTokenHint', kind: 'hint', status: 'known-unrendered', causa: 'informativo/cosmético (contador de token)' },
  { id: 'icon:HINT_ICON_BAD', kind: 'icon', status: 'rendered', ref: 'web/src/utils/textRefs.ts:10' },
  { id: 'icon:HINT_ICON_DUNGEON_ROOM_CURRENT', kind: 'icon', status: 'known-unrendered', causa: 'icono interno; el progreso del dungeon se pinta en MechanicsTray.tsx:103' },
  { id: 'icon:HINT_ICON_DUNGEON_ROOM_NEXT', kind: 'icon', status: 'known-unrendered', causa: 'icono interno; el progreso del dungeon se pinta en MechanicsTray.tsx:103' },
  { id: 'icon:HINT_ICON_GOOD', kind: 'icon', status: 'rendered', ref: 'web/src/utils/textRefs.ts:9' },
  { id: 'icon:HINT_ICON_REQUIRE', kind: 'icon', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'icon:HINT_ICON_RESTRICT', kind: 'icon', status: 'rendered', ref: 'web/src/board/CardIcons.tsx:27' },
  { id: 'mark:hintstart', kind: 'rules', status: 'rendered', ref: 'web/src/game/FormattedText.tsx:180' },
  { id: 'info:Commander', kind: 'info', status: 'rendered', ref: 'web/src/game/CommanderDamageMatrix.tsx:91' },
  { id: 'info:_modeChoice', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (modo elegido; línea de reglas)' },
  { id: 'info:attachedTo', kind: 'info', status: 'known-unrendered', causa: 'libro mayor interno (el valor se borra con null; sin texto)' },
  { id: 'info:chosen color', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de color; línea de reglas)' },
  { id: 'info:chosen creature', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de criatura; línea de reglas)' },
  { id: 'info:chosen opponent', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de oponente; línea de reglas)' },
  { id: 'info:chosen player', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de jugador; línea de reglas)' },
  { id: 'info:chosen set', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de edición; línea de reglas)' },
  { id: 'info:chosen type', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (elección de tipo; línea de reglas)' },
  { id: 'info:hauntinfo', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (haunt; línea de reglas)' },
  { id: 'info:protector', kind: 'info', status: 'rendered', ref: 'web/src/board/designations.ts:47' },
  { id: 'info:soulbond', kind: 'info', status: 'rendered', ref: 'web/src/board/designations.ts:48' },
  { id: 'info:IS_PREPARED', kind: 'info', status: 'rendered', ref: 'web/src/board/designations.ts:46' },
  { id: 'info:IS_RINGBEARER', kind: 'info', status: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:61' },
  { id: 'info:IS_SUSPECTED', kind: 'info', status: 'rendered', ref: 'web/src/board/designations.ts:33' },
  { id: 'info:NAMED_CARD', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (nombre elegido; línea de reglas)' },
  { id: 'info:_secOpp', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (oponente secreto; línea de reglas)' },
  { id: 'info:"Commander" + entry.getKey()', kind: 'info', status: 'rendered', ref: 'web/src/game/CommanderDamageMatrix.tsx:91' },
  { id: 'info:"detain" + getId()', kind: 'info', status: 'known-unrendered', causa: 'informativo/cosmético (estado Detained; línea de reglas)' },
]
