export type EngineViewDecision = 'rendered' | 'accepted' | 'bookkeeping' | 'parser-artifact' | 'duplicado'
export type EngineViewImpact = 'alto' | 'medio' | 'bajo' | 'nulo'
export type EngineViewName = 'PermanentView' | 'PlayerView' | 'GameView'

export interface EngineViewRegistryRow {
  id: string
  view: EngineViewName
  field: string
  impacto: EngineViewImpact
  decision: EngineViewDecision
  causa?: string
  ref?: string
}

export function engineViewKey(view: string, field: string): string {
  return `${view}.${field}`
}

export const ENGINE_VIEW_REGISTRY: EngineViewRegistryRow[] = [
  { id: 'PermanentView.abilities', view: 'PermanentView', field: 'abilities', impacto: 'nulo', decision: 'accepted', causa: 'objetos Ability del motor; el texto y los iconos llegan en rules/cardIcons' },
  { id: 'PermanentView.addCounters', view: 'PermanentView', field: 'addCounters', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class MarkedDamageInfo (PermanentImpl.java:55-66), no de PermanentImpl' },
  { id: 'PermanentView.attachedToZoneChangeCounter', view: 'PermanentView', field: 'attachedToZoneChangeCounter', impacto: 'nulo', decision: 'bookkeeping', causa: 'contador interno de zona para efectos de vínculo; la relación visible llega por attachedTo' },
  { id: 'PermanentView.attacking', view: 'PermanentView', field: 'attacking', impacto: 'nulo', decision: 'duplicado', causa: 'el atacante y su defensor llegan en GameView.combat' },
  { id: 'PermanentView.beforeResetControllerId', view: 'PermanentView', field: 'beforeResetControllerId', impacto: 'nulo', decision: 'bookkeeping', causa: 'controlador previo para deshacer efectos de control; no se muestra' },
  { id: 'PermanentView.blocking', view: 'PermanentView', field: 'blocking', impacto: 'nulo', decision: 'duplicado', causa: 'los bloqueos llegan en GameView.combat' },
  { id: 'PermanentView.blockingSet', view: 'PermanentView', field: 'blockingSet', impacto: 'nulo', decision: 'duplicado', causa: 'los bloqueos llegan en GameView.combat' },
  { id: 'PermanentView.canBeSacrificed', view: 'PermanentView', field: 'canBeSacrificed', impacto: 'bajo', decision: 'accepted', causa: 'restricción usada por el motor; el server ya filtra las acciones ofrecidas' },
  { id: 'PermanentView.cardType', view: 'PermanentView', field: 'cardType', impacto: 'nulo', decision: 'duplicado', causa: 'los tipos llegan en CardView.cardTypes' },
  { id: 'PermanentView.classLevel', view: 'PermanentView', field: 'classLevel', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:42', causa: 'la línea "Class level: N" llega en rules y se parsea' },
  { id: 'PermanentView.controlledFromStartOfControllerTurn', view: 'PermanentView', field: 'controlledFromStartOfControllerTurn', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca temporal interna para disparos de "desde el inicio del turno"' },
  { id: 'PermanentView.copyFrom', view: 'PermanentView', field: 'copyFrom', impacto: 'nulo', decision: 'duplicado', causa: 'la copia se marca con CardView.copy/nameOwner' },
  { id: 'PermanentView.counter', view: 'PermanentView', field: 'counter', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class MarkedDamageInfo (PermanentImpl.java:55-66), no de PermanentImpl' },
  { id: 'PermanentView.createOrder', view: 'PermanentView', field: 'createOrder', impacto: 'nulo', decision: 'bookkeeping', causa: 'orden interno de creación de permanentes' },
  { id: 'PermanentView.dealtDamageByThisTurn', view: 'PermanentView', field: 'dealtDamageByThisTurn', impacto: 'nulo', decision: 'bookkeeping', causa: 'registro interno de daño para disparos y condiciones' },
  { id: 'PermanentView.deathtouched', view: 'PermanentView', field: 'deathtouched', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca interna de daño con toque mortal' },
  { id: 'PermanentView.flipCardName', view: 'PermanentView', field: 'flipCardName', impacto: 'nulo', decision: 'duplicado', causa: 'el nombre alterno llega en CardView.alternateName (PermanentView.java:81)' },
  { id: 'PermanentView.goadingPlayers', view: 'PermanentView', field: 'goadingPlayers', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/CardIcons.tsx:27', causa: 'goad llega en cardIcons (OTHER_HAS_RESTRICTIONS) + línea "Goaded by..." en rules' },
  { id: 'PermanentView.harnessed', view: 'PermanentView', field: 'harnessed', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:44', causa: 'la línea "{this} is harnessed" llega en rules y se parsea' },
  { id: 'PermanentView.indirectPhase', view: 'PermanentView', field: 'indirectPhase', impacto: 'nulo', decision: 'bookkeeping', causa: 'faseo indirecto interno; phasedIn ya se emite' },
  { id: 'PermanentView.info', view: 'PermanentView', field: 'info', impacto: 'nulo', decision: 'duplicado', causa: 'sus líneas se funden en CardView.rules' },
  { id: 'PermanentView.leftHalfUnlocked', view: 'PermanentView', field: 'leftHalfUnlocked', impacto: 'bajo', decision: 'accepted', causa: 'Room (Duskmourn); el motor solo lo informa por chat (PermanentImpl.java:2336-2364) y el desktop tampoco lo lee' },
  { id: 'PermanentView.legendRuleApplies', view: 'PermanentView', field: 'legendRuleApplies', impacto: 'nulo', decision: 'bookkeeping', causa: 'excepción a la regla de legendarias; afecta al motor, no al render' },
  { id: 'PermanentView.loyaltyActivationsAvailable', view: 'PermanentView', field: 'loyaltyActivationsAvailable', impacto: 'bajo', decision: 'accepted', causa: 'el server ya filtra las habilidades de planeswalker jugables (canPlayObjects)' },
  { id: 'PermanentView.manaCost', view: 'PermanentView', field: 'manaCost', impacto: 'nulo', decision: 'duplicado', causa: 'el coste llega en CardView.manaCostLeftStr/manaCostRightStr/manaValue' },
  { id: 'PermanentView.markedDamage', view: 'PermanentView', field: 'markedDamage', impacto: 'nulo', decision: 'bookkeeping', causa: 'daño marcado por fuente (regeneración); el total llega en damage' },
  { id: 'PermanentView.markedLifelink', view: 'PermanentView', field: 'markedLifelink', impacto: 'nulo', decision: 'bookkeeping', causa: 'registro interno de daño con vínculo vital' },
  { id: 'PermanentView.maxBlockedBy', view: 'PermanentView', field: 'maxBlockedBy', impacto: 'bajo', decision: 'accepted', causa: 'restricción de bloqueos aplicada por el server; el resultado llega por canBlock/cardIcons' },
  { id: 'PermanentView.maxBlocks', view: 'PermanentView', field: 'maxBlocks', impacto: 'bajo', decision: 'accepted', causa: 'restricción de bloqueos aplicada por el server; el resultado llega por canBlock/cardIcons' },
  { id: 'PermanentView.meldsToCard', view: 'PermanentView', field: 'meldsToCard', impacto: 'nulo', decision: 'duplicado', causa: 'la carta meld resultante llega en CardView.secondCardFace (CardView.java:588)' },
  { id: 'PermanentView.minBlockedBy', view: 'PermanentView', field: 'minBlockedBy', impacto: 'bajo', decision: 'accepted', causa: 'restricción de bloqueos aplicada por el server; el resultado llega por canBlock/cardIcons' },
  { id: 'PermanentView.monstrous', view: 'PermanentView', field: 'monstrous', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:36', causa: 'la línea "{this} is monstrous" llega en rules y se parsea' },
  { id: 'PermanentView.morphCard', view: 'PermanentView', field: 'morphCard', impacto: 'nulo', decision: 'duplicado', causa: 'el estado boca abajo llega en CardView.faceDown y PermanentView.morphed' },
  { id: 'PermanentView.mutatedAbilities', view: 'PermanentView', field: 'mutatedAbilities', impacto: 'nulo', decision: 'duplicado', causa: 'las habilidades de la pila mutate se funden en rules' },
  { id: 'PermanentView.mutations', view: 'PermanentView', field: 'mutations', impacto: 'nulo', decision: 'duplicado', causa: 'la pila mutate llega en PermanentView.mutateView' },
  { id: 'PermanentView.mutationsForView', view: 'PermanentView', field: 'mutationsForView', impacto: 'nulo', decision: 'duplicado', causa: 'la pila mutate llega en PermanentView.mutateView (PermanentView.java:74)' },
  { id: 'PermanentView.nightCard', view: 'PermanentView', field: 'nightCard', impacto: 'nulo', decision: 'duplicado', causa: 'el lado noche llega en transformable/secondCardFace' },
  { id: 'PermanentView.objectId', view: 'PermanentView', field: 'objectId', impacto: 'nulo', decision: 'duplicado', causa: 'el id llega en CardView.id' },
  { id: 'PermanentView.originalControllerId', view: 'PermanentView', field: 'originalControllerId', impacto: 'nulo', decision: 'bookkeeping', causa: 'controlador original para efectos de control; no se muestra' },
  { id: 'PermanentView.ownerId', view: 'PermanentView', field: 'ownerId', impacto: 'nulo', decision: 'duplicado', causa: 'la propiedad llega por controlledByOwner/nameOwner' },
  { id: 'PermanentView.pairedPermanent', view: 'PermanentView', field: 'pairedPermanent', impacto: 'nulo', decision: 'duplicado', causa: 'el vínculo llega en CardView.pairedCard y en la designación "paired"' },
  { id: 'PermanentView.prepared', view: 'PermanentView', field: 'prepared', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:46', causa: 'la línea "Prepared" llega en rules y se parsea' },
  { id: 'PermanentView.protectorId', view: 'PermanentView', field: 'protectorId', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:47', causa: 'la línea "Protected by ..." llega en rules y se parsea' },
  { id: 'PermanentView.prototyped', view: 'PermanentView', field: 'prototyped', impacto: 'nulo', decision: 'bookkeeping', causa: 'el server ya aplica las características prototipo; el flag no se muestra' },
  { id: 'PermanentView.renowned', view: 'PermanentView', field: 'renowned', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:36', causa: 'la línea "{this} is renowned" llega en rules y se parsea' },
  { id: 'PermanentView.rightHalfUnlocked', view: 'PermanentView', field: 'rightHalfUnlocked', impacto: 'bajo', decision: 'accepted', causa: 'Room (Duskmourn); el motor solo lo informa por chat (PermanentImpl.java:2336-2364) y el desktop tampoco lo lee' },
  { id: 'PermanentView.ringBearerFlag', view: 'PermanentView', field: 'ringBearerFlag', impacto: 'nulo', decision: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:61', causa: 'el portador llega en cardIcons (RINGBEARER) y se busca por el campo' },
  { id: 'PermanentView.roomWasUnlockedOnCast', view: 'PermanentView', field: 'roomWasUnlockedOnCast', impacto: 'bajo', decision: 'accepted', causa: 'Room (Duskmourn); el motor solo lo informa por chat (PermanentImpl.java:2336-2364) y el desktop tampoco lo lee' },
  { id: 'PermanentView.secondSideCard', view: 'PermanentView', field: 'secondSideCard', impacto: 'nulo', decision: 'duplicado', causa: 'la otra cara llega en CardView.secondCardFace' },
  { id: 'PermanentView.solved', view: 'PermanentView', field: 'solved', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:43', causa: 'la línea "Case is solved" llega en rules y se parsea' },
  { id: 'PermanentView.sourceObject', view: 'PermanentView', field: 'sourceObject', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class MarkedDamageInfo (PermanentImpl.java:55-66), no de PermanentImpl' },
  { id: 'PermanentView.spellAbility', view: 'PermanentView', field: 'spellAbility', impacto: 'nulo', decision: 'bookkeeping', causa: 'la habilidad jugable llega por canPlayObjects/stack' },
  { id: 'PermanentView.subtype', view: 'PermanentView', field: 'subtype', impacto: 'nulo', decision: 'duplicado', causa: 'los subtipos llegan en CardView.subTypes' },
  { id: 'PermanentView.supertype', view: 'PermanentView', field: 'supertype', impacto: 'nulo', decision: 'duplicado', causa: 'los supertipos llegan en CardView.superTypes' },
  { id: 'PermanentView.suspected', view: 'PermanentView', field: 'suspected', impacto: 'nulo', decision: 'rendered', ref: 'web/src/board/designations.ts:40', causa: 'la línea "Suspected" llega en rules y se parsea' },
  { id: 'PermanentView.text', view: 'PermanentView', field: 'text', impacto: 'nulo', decision: 'duplicado', causa: 'el texto llega en CardView.rules' },
  { id: 'PermanentView.timesLoyaltyUsed', view: 'PermanentView', field: 'timesLoyaltyUsed', impacto: 'nulo', decision: 'bookkeeping', causa: 'contador interno de usos de lealtad' },
  { id: 'PermanentView.topMutation', view: 'PermanentView', field: 'topMutation', impacto: 'nulo', decision: 'duplicado', causa: 'la carta superior de la pila mutate llega en PermanentView.mutateView' },
  { id: 'PermanentView.transformCount', view: 'PermanentView', field: 'transformCount', impacto: 'nulo', decision: 'bookkeeping', causa: 'contador interno de transformaciones' },
  { id: 'PermanentView.turnsOnBattlefield', view: 'PermanentView', field: 'turnsOnBattlefield', impacto: 'nulo', decision: 'bookkeeping', causa: 'contador interno de turnos en el campo de batalla' },
  { id: 'PlayerView.abilities', view: 'PlayerView', field: 'abilities', impacto: 'medio', decision: 'accepted', causa: 'habilidades de jugador (emblemas/efectos); el DTO no tiene canal' },
  { id: 'PlayerView.abort', view: 'PlayerView', field: 'abort', impacto: 'nulo', decision: 'bookkeeping', causa: 'bandera de aborto del hilo de juego' },
  { id: 'PlayerView.alternativeSourceCosts', view: 'PlayerView', field: 'alternativeSourceCosts', impacto: 'bajo', decision: 'accepted', causa: 'la superficie jugable llega por canPlayObjects/GAME_CHOOSE_ABILITY' },
  { id: 'PlayerView.approvingObject', view: 'PlayerView', field: 'approvingObject', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class ApprovingObjectResult (PlayerImpl.java:1512-1514)' },
  { id: 'PlayerView.canGainLife', view: 'PlayerView', field: 'canGainLife', impacto: 'bajo', decision: 'accepted', causa: 'restricción global (efectos que prohíben ganar vida); sin canal' },
  { id: 'PlayerView.canLoseLife', view: 'PlayerView', field: 'canLoseLife', impacto: 'bajo', decision: 'accepted', causa: 'restricción global (efectos que prohíben perder vida); sin canal' },
  { id: 'PlayerView.canPlotFromTopOfLibrary', view: 'PlayerView', field: 'canPlotFromTopOfLibrary', impacto: 'bajo', decision: 'accepted', causa: 'la oferta de Plot viaja en canPlayObjects' },
  { id: 'PlayerView.commandersIds', view: 'PlayerView', field: 'commandersIds', impacto: 'nulo', decision: 'duplicado', causa: 'los comandantes llegan en commandList y en CommanderDamageMatrix' },
  { id: 'PlayerView.dateLastAddedToStack', view: 'PlayerView', field: 'dateLastAddedToStack', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca temporal interna de prioridad' },
  { id: 'PlayerView.designations', view: 'PlayerView', field: 'designations', impacto: 'nulo', decision: 'rendered', ref: 'web/src/game/MechanicsTray.tsx:142', causa: 'llegan como designationNames (PlayerView.java:156-158) y se pintan en MechanicsTray/PlayerInfoBar' },
  { id: 'PlayerView.draws', view: 'PlayerView', field: 'draws', impacto: 'nulo', decision: 'bookkeeping', causa: 'bandera interna de robo del turno' },
  { id: 'PlayerView.drawsFromBottom', view: 'PlayerView', field: 'drawsFromBottom', impacto: 'bajo', decision: 'accepted', causa: 'política de robo (formato); no se muestra' },
  { id: 'PlayerView.drawsOnOpponentsTurn', view: 'PlayerView', field: 'drawsOnOpponentsTurn', impacto: 'bajo', decision: 'accepted', causa: 'política de robo (formato); no se muestra' },
  { id: 'PlayerView.hand', view: 'PlayerView', field: 'hand', impacto: 'nulo', decision: 'duplicado', causa: 'la mano llega en myHand/opponentHands/handCount' },
  { id: 'PlayerView.human', view: 'PlayerView', field: 'human', impacto: 'nulo', decision: 'duplicado', causa: 'isHuman' },
  { id: 'PlayerView.idleTimeout', view: 'PlayerView', field: 'idleTimeout', impacto: 'nulo', decision: 'duplicado', causa: 'el tiempo visible es priorityTimeLeftSecs' },
  { id: 'PlayerView.inRange', view: 'PlayerView', field: 'inRange', impacto: 'bajo', decision: 'accepted', causa: 'rango de influencia multijugador; el desktop tampoco lo muestra' },
  { id: 'PlayerView.isFastFailInTestMode', view: 'PlayerView', field: 'isFastFailInTestMode', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag de modo test' },
  { id: 'PlayerView.isGameUnderControl', view: 'PlayerView', field: 'isGameUnderControl', impacto: 'nulo', decision: 'bookkeeping', causa: 'el control se deriva en web/src/state/control.ts (opponentHands)' },
  { id: 'PlayerView.isTestMode', view: 'PlayerView', field: 'isTestMode', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag de modo test' },
  { id: 'PlayerView.justActivatedType', view: 'PlayerView', field: 'justActivatedType', impacto: 'nulo', decision: 'bookkeeping', causa: 'tipo de la última habilidad activada (interno)' },
  { id: 'PlayerView.landsPerTurn', view: 'PlayerView', field: 'landsPerTurn', impacto: 'bajo', decision: 'accepted', causa: 'límite de tierras por turno; sin canal' },
  { id: 'PlayerView.landsPlayed', view: 'PlayerView', field: 'landsPlayed', impacto: 'bajo', decision: 'accepted', causa: 'tierras jugadas este turno; sin canal' },
  { id: 'PlayerView.left', view: 'PlayerView', field: 'left', impacto: 'nulo', decision: 'duplicado', causa: 'hasLeft' },
  { id: 'PlayerView.library', view: 'PlayerView', field: 'library', impacto: 'nulo', decision: 'duplicado', causa: 'libraryCount y topCard (revelado)' },
  { id: 'PlayerView.loseByZeroOrLessLife', view: 'PlayerView', field: 'loseByZeroOrLessLife', impacto: 'bajo', decision: 'accepted', causa: 'regla de derrota por vida 0 o menos; sin canal' },
  { id: 'PlayerView.loses', view: 'PlayerView', field: 'loses', impacto: 'nulo', decision: 'bookkeeping', causa: 'bandera interna de derrota' },
  { id: 'PlayerView.matchPlayer', view: 'PlayerView', field: 'matchPlayer', impacto: 'nulo', decision: 'duplicado', causa: 'el marcador del match llega en wins/winsNeeded' },
  { id: 'PlayerView.maxAttackedBy', view: 'PlayerView', field: 'maxAttackedBy', impacto: 'bajo', decision: 'accepted', causa: 'límite de atacantes; el server ya filtra el combate' },
  { id: 'PlayerView.maxHandSize', view: 'PlayerView', field: 'maxHandSize', impacto: 'bajo', decision: 'accepted', causa: 'tamaño máximo de mano (descarte); sin canal' },
  { id: 'PlayerView.modifier', view: 'PlayerView', field: 'modifier', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class RollDieResult (PlayerImpl.java:3198-3207)' },
  { id: 'PlayerView.naturalResult', view: 'PlayerView', field: 'naturalResult', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class RollDieResult (PlayerImpl.java:3198-3207)' },
  { id: 'PlayerView.passed', view: 'PlayerView', field: 'passed', impacto: 'nulo', decision: 'duplicado', causa: 'passedTurn/passedUntilEndOfTurn/passedUntilNextMain/... en PlayerView' },
  { id: 'PlayerView.passedTurnSkipStack', view: 'PlayerView', field: 'passedTurnSkipStack', impacto: 'nulo', decision: 'bookkeeping', causa: 'variante interna de pase de prioridad' },
  { id: 'PlayerView.payLifeCostRestrictions', view: 'PlayerView', field: 'payLifeCostRestrictions', impacto: 'bajo', decision: 'accepted', causa: 'restricciones de pago de vida; el server filtra el pago' },
  { id: 'PlayerView.payManaMode', view: 'PlayerView', field: 'payManaMode', impacto: 'nulo', decision: 'bookkeeping', causa: 'modo de pago (auto/manual) de la UI; el pago llega por prompts' },
  { id: 'PlayerView.phyrexianColors', view: 'PlayerView', field: 'phyrexianColors', impacto: 'bajo', decision: 'accepted', causa: 'superficie de pago pirexiano vía canPlayObjects' },
  { id: 'PlayerView.planarResult', view: 'PlayerView', field: 'planarResult', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class RollDieResult (PlayerImpl.java:3198-3207)' },
  { id: 'PlayerView.playersUnderYourControl', view: 'PlayerView', field: 'playersUnderYourControl', impacto: 'nulo', decision: 'bookkeeping', causa: 'el control se deriva en web/src/state/control.ts' },
  { id: 'PlayerView.priorityTimeLeft', view: 'PlayerView', field: 'priorityTimeLeft', impacto: 'nulo', decision: 'duplicado', causa: 'priorityTimeLeftSecs' },
  { id: 'PlayerView.quit', view: 'PlayerView', field: 'quit', impacto: 'nulo', decision: 'duplicado', causa: 'hasLeft' },
  { id: 'PlayerView.range', view: 'PlayerView', field: 'range', impacto: 'bajo', decision: 'accepted', causa: 'rango de influencia multijugador; no se muestra' },
  { id: 'PlayerView.reachedNextTurnAfterLeaving', view: 'PlayerView', field: 'reachedNextTurnAfterLeaving', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca interna para reincorporación a la partida' },
  { id: 'PlayerView.skippedAtLeastOnce', view: 'PlayerView', field: 'skippedAtLeastOnce', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca interna de turnos saltados' },
  { id: 'PlayerView.speed', view: 'PlayerView', field: 'speed', impacto: 'medio', decision: 'accepted', causa: 'nivel 1-4 no emitido por upstream; la presencia llega vía designationNames y se pinta', ref: 'web/src/game/PlayerInfoBar.tsx:201' },
  { id: 'PlayerView.status', view: 'PlayerView', field: 'status', impacto: 'nulo', decision: 'parser-artifact', causa: 'campo de la inner class ApprovingObjectResult (PlayerImpl.java:1506-1514)' },
  { id: 'PlayerView.storedBookmark', view: 'PlayerView', field: 'storedBookmark', impacto: 'nulo', decision: 'duplicado', causa: 'statesSavedSize' },
  { id: 'PlayerView.timerTimeout', view: 'PlayerView', field: 'timerTimeout', impacto: 'nulo', decision: 'duplicado', causa: 'los badges de timer se derivan de timerActive/priorityTimeLeftSecs' },
  { id: 'PlayerView.topCardRevealed', view: 'PlayerView', field: 'topCardRevealed', impacto: 'nulo', decision: 'duplicado', causa: 'topCard' },
  { id: 'PlayerView.turnController', view: 'PlayerView', field: 'turnController', impacto: 'nulo', decision: 'bookkeeping', causa: 'el control de turno se deriva en web/src/state/control.ts' },
  { id: 'PlayerView.turnControllers', view: 'PlayerView', field: 'turnControllers', impacto: 'nulo', decision: 'bookkeeping', causa: 'el control de turno se deriva en web/src/state/control.ts' },
  { id: 'PlayerView.turns', view: 'PlayerView', field: 'turns', impacto: 'nulo', decision: 'bookkeeping', causa: 'contador interno de turnos del jugador' },
  { id: 'PlayerView.usersAllowedToSeeHandCards', view: 'PlayerView', field: 'usersAllowedToSeeHandCards', impacto: 'nulo', decision: 'bookkeeping', causa: 'visibilidad interna de manos (watching); el server ya filtra opponentHands' },
  { id: 'GameView.aiGame', view: 'GameView', field: 'aiGame', impacto: 'nulo', decision: 'bookkeeping', causa: 'bandera de partida IA vs IA' },
  { id: 'GameView.attackOption', view: 'GameView', field: 'attackOption', impacto: 'nulo', decision: 'bookkeeping', causa: 'opción de ataque multijugador (config de partida)' },
  { id: 'GameView.checkPlayableState', view: 'GameView', field: 'checkPlayableState', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag interno de recálculo de jugabilidad' },
  { id: 'GameView.concedingPlayers', view: 'GameView', field: 'concedingPlayers', impacto: 'nulo', decision: 'bookkeeping', causa: 'cola de concesiones; el efecto llega por hasLeft/GAME_END' },
  { id: 'GameView.endTime', view: 'GameView', field: 'endTime', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca temporal de fin; no se muestra' },
  { id: 'GameView.enterWithCounters', view: 'GameView', field: 'enterWithCounters', impacto: 'nulo', decision: 'bookkeeping', causa: 'contadores de entrada; el resultado llega en counters' },
  { id: 'GameView.gameCards', view: 'GameView', field: 'gameCards', impacto: 'nulo', decision: 'bookkeeping', causa: 'registro interno de cartas del motor' },
  { id: 'GameView.gameIndex', view: 'GameView', field: 'gameIndex', impacto: 'nulo', decision: 'bookkeeping', causa: 'índice de la partida en el match; el marcador llega en wins/winsNeeded' },
  { id: 'GameView.gameOptions', view: 'GameView', field: 'gameOptions', impacto: 'nulo', decision: 'bookkeeping', causa: 'bolsa de opciones del motor; la UI usa la superficie ya expuesta' },
  { id: 'GameView.gameStopped', view: 'GameView', field: 'gameStopped', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag interno de partida detenida' },
  { id: 'GameView.id', view: 'GameView', field: 'id', impacto: 'nulo', decision: 'duplicado', causa: 'el gameId llega en GAME_INIT/GAME_UPDATE del proxy' },
  { id: 'GameView.meldCards', view: 'GameView', field: 'meldCards', impacto: 'nulo', decision: 'bookkeeping', causa: 'registro interno de cartas meld' },
  { id: 'GameView.minimumDeckSize', view: 'GameView', field: 'minimumDeckSize', impacto: 'nulo', decision: 'bookkeeping', causa: 'configuración de mazo mínimo; no se muestra' },
  { id: 'GameView.mulligan', view: 'GameView', field: 'mulligan', impacto: 'nulo', decision: 'bookkeeping', causa: 'estado del mulligan; la decisión llega por prompt' },
  { id: 'GameView.range', view: 'GameView', field: 'range', impacto: 'bajo', decision: 'accepted', causa: 'rango de influencia multijugador (config); no se muestra' },
  { id: 'GameView.ready', view: 'GameView', field: 'ready', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag interno de partida lista' },
  { id: 'GameView.saveGame', view: 'GameView', field: 'saveGame', impacto: 'nulo', decision: 'bookkeeping', causa: 'bandera de guardado; no se muestra' },
  { id: 'GameView.scopeRelevant', view: 'GameView', field: 'scopeRelevant', impacto: 'nulo', decision: 'bookkeeping', causa: 'caché interna de objetos relevantes' },
  { id: 'GameView.simulation', view: 'GameView', field: 'simulation', impacto: 'nulo', decision: 'bookkeeping', causa: 'flag de partida de simulación' },
  { id: 'GameView.startMessage', view: 'GameView', field: 'startMessage', impacto: 'nulo', decision: 'duplicado', causa: 'se emite como status event al arrancar (GameImpl.java:1258)' },
  { id: 'GameView.startTime', view: 'GameView', field: 'startTime', impacto: 'nulo', decision: 'bookkeeping', causa: 'marca temporal de inicio; no se muestra' },
  { id: 'GameView.startingHandSize', view: 'GameView', field: 'startingHandSize', impacto: 'nulo', decision: 'bookkeeping', causa: 'configuración inicial; no se muestra tras el arranque' },
  { id: 'GameView.startingLife', view: 'GameView', field: 'startingLife', impacto: 'nulo', decision: 'bookkeeping', causa: 'la vida actual llega en PlayerView.life' },
  { id: 'GameView.startingPlayerId', view: 'GameView', field: 'startingPlayerId', impacto: 'nulo', decision: 'duplicado', causa: 'quién empieza se deduce de activePlayerId/turn' },
  { id: 'GameView.state', view: 'GameView', field: 'state', impacto: 'nulo', decision: 'bookkeeping', causa: 'máquina de estados interna; phase/step/turn ya se emiten' },
  { id: 'GameView.tableId', view: 'GameView', field: 'tableId', impacto: 'nulo', decision: 'duplicado', causa: 'el tableId lo gestiona el proxy/lobby (TableClientMessage.tableId)' },
  { id: 'GameView.winnerId', view: 'GameView', field: 'winnerId', impacto: 'nulo', decision: 'duplicado', causa: 'el ganador llega por el evento de fin de partida (GAME_END)' },
]
