import { describe, expect, it } from 'vitest'

// @ts-expect-error node: specifiers are not in the DOM lib; this test runs in Node under vitest
import { readFileSync, existsSync, readdirSync } from 'node:fs'
// @ts-expect-error node: specifiers are not in the DOM lib; this test runs in Node under vitest
import { fileURLToPath } from 'node:url'
// @ts-expect-error node: specifiers are not in the DOM lib; this test runs in Node under vitest
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))

// Oracle: exhaustive serializable fields of the XMage view classes, generated by
// `scripts/view-schema.mjs` from the Java source (see JsonUtil reflection rules).
const SERVER_SCHEMA = resolve(here, '../../fixtures/server-view-schema.json')
// What the web client actually models (source of truth for modeled fields).
const CONTRACT = resolve(here, '../../schema/contract.schema.json')

function loadJson(p: string) {
  return JSON.parse(readFileSync(p, 'utf8'))
}

const server = loadJson(SERVER_SCHEMA) as {
  cardFields: string[]
  playerFields: string[]
  gameViewFields: string[]
}
const contract = loadJson(CONTRACT)
const defs = contract.definitions

function propKeys(...names: string[]): Set<string> {
  const s = new Set<string>()
  for (const n of names) {
    const d = defs[n]
    if (d && d.properties) for (const k of Object.keys(d.properties)) s.add(k)
  }
  return s
}

// Fields we intentionally don't model in the client (self-referential / internal
// server objects). Reviewed, not auto-detected — if a *new* server field ever
// appears here it must be justified, exactly like callbackCoverage's KNOWN_UNHANDLED.
const ALLOWED_EXTRA = new Set<string>([])

const MODELED_CARD = propKeys('CardView', 'PermanentView')
const MODELED_PLAYER = propKeys('PlayerView')
const MODELED_GAMEVIEW = propKeys('GameView')

describe('mechanics reverse-drift: server-emitted fields are modeled', () => {
  it('every serializable card/permanent field is modeled in CardView/PermanentView', () => {
    const missing = server.cardFields.filter((f) => !MODELED_CARD.has(f) && !ALLOWED_EXTRA.has(f))
    expect(missing, `Campos del server sin modelar (card): ${missing.join(', ')}`).toEqual([])
  })

  it('every serializable player field is modeled in PlayerView', () => {
    const missing = server.playerFields.filter((f) => !MODELED_PLAYER.has(f) && !ALLOWED_EXTRA.has(f))
    expect(missing, `Campos del server sin modelar (player): ${missing.join(', ')}`).toEqual([])
  })

  it('every serializable gameView field is modeled in GameView', () => {
    const missing = server.gameViewFields.filter((f) => !MODELED_GAMEVIEW.has(f) && !ALLOWED_EXTRA.has(f))
    expect(missing, `Campos del server sin modelar (gameView): ${missing.join(', ')}`).toEqual([])
  })
})

// Cross-check: the Java parser (scripts/view-schema.mjs) could miss a field. By
// scanning every card/player object in the committed real-server recorded frames
// we verify that every key the server actually emits is inside the oracle set.
describe('mechanics reverse-drift: committed frames match the oracle', () => {
  const recordedDir = resolve(here, '../../fixtures/recorded')
  if (!existsSync(recordedDir)) return

  function* walk(value: unknown, onObj: (o: Record<string, unknown>) => void): Generator<void> {
    if (Array.isArray(value)) {
      for (const v of value) yield* walk(v, onObj)
    } else if (value && typeof value === 'object') {
      const o = value as Record<string, unknown>
      onObj(o)
      for (const v of Object.values(o)) yield* walk(v, onObj)
    }
  }

  const cardEmitted = new Set<string>()
  const playerEmitted = new Set<string>()
  const gameViewEmitted = new Set<string>()

  for (const file of readdirSync(recordedDir)) {
    if (file === 'manifest.json' || !file.endsWith('.json')) continue
    const raw = loadJson(resolve(recordedDir, file))
    const view = raw.gameView
    if (!view || typeof view !== 'object') continue
    walk(view, (o) => {
      if ('manaValue' in o) for (const k of Object.keys(o)) cardEmitted.add(k)
      if ('playerId' in o) for (const k of Object.keys(o)) playerEmitted.add(k)
    })
    for (const k of Object.keys(view as Record<string, unknown>)) gameViewEmitted.add(k)
  }

  it('recorded card keys are within the server oracle', () => {
    const unknown = [...cardEmitted].filter((k) => !server.cardFields.includes(k))
    expect(unknown, `Claves de carta emitidas que el oráculo no lista (¿parser desactualizado?): ${unknown.join(', ')}`).toEqual([])
  })

  it('recorded player keys are within the server oracle', () => {
    const unknown = [...playerEmitted].filter((k) => !server.playerFields.includes(k))
    expect(unknown, `Claves de jugador emitidas que el oráculo no lista: ${unknown.join(', ')}`).toEqual([])
  })

  it('recorded gameView keys are within the server oracle', () => {
    const union = new Set([...server.gameViewFields, ...MODELED_GAMEVIEW])
    const unknown = [...gameViewEmitted].filter((k) => !union.has(k))
    expect(unknown, `Claves de gameView emitidas que el oráculo no lista: ${unknown.join(', ')}`).toEqual([])
  })
})
